### ISSUE TITLE
Unable to create observer model from config.xml

### ISSUE THREAD

**Issue by MagePsycho** [enriquepiatti/Magicento#101]
When I tried to create observer model it gave me the following error notification:
"Magicento Notification: Error trying to create class: MagePsycho_Catlayout_Model_Observer in: nullModel/Observer.php"

Is this a bug or am I missing something?

**Comment by MagePsycho** [comment]
When I restarted the IDE, then it worked. Not sure if it's a issue or else.

**Comment by enriquepiatti** [comment]
I think it was a problem with the index. Please reopen if you are see the error again.
