### ISSUE TITLE
invalid XML generated by Layout update file creator

### ISSUE THREAD

**Issue by MagePsycho** [enriquepiatti/Magicento#102]
Minor bug though, thought worth mentioning:
Pressing :
`Alt + Enter > Create Layout Update File > Chosing proper theme folder` > it creates [module].xml with the following code:

``` XML
<layout>
</layout>
```

Which should be at least:

``` XML
<?xml version="1.0"?>
<layout version="0.1.0">
</layout>
```

**Comment by enriquepiatti** [comment]
fixed in v2.6
