### ISSUE TITLE
System.xml - Source model autocomplete for custom modules

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#105]
I my system.xml file I have next section:

``` xml
<my_field translate="label">
    <label>My Field</label>
    <frontend_type>select</frontend_type>
    <source_model>my_module/adminhtml_system_config_source_my_custom_model</source_model>
    <show_in_default>1</show_in_default>
    <show_in_website>0</show_in_website>
    <show_in_store>0</show_in_store>
    <sort_order>2000</sort_order>
    <depends>
        <enabled>1</enabled>
    </depends>
</my_field>
```

When I change source model and type "adminhtml" I have autocomplete for source models, but for my own source models I haven't autocomplete. Would be great have ability have autocomplete to my own source models.
We may filter this models by present toOptionArray() method

**Comment by ihor-sviziev** [comment]
Also I have not all source models from adminhtml module in my list, example:
- adminhtml/system_config_source_website
- adminhtml/system_config_source_price_step
- adminhtml/system_config_source_order_status_new
- adminhtml/system_config_source_order_status_processing

**Comment by enriquepiatti** [comment]
done in v2.6.5. Thanks!

**Comment by ihor-sviziev** [comment]
Works great, thanks!

**Comment by ihor-sviziev** [comment]
@enriquepiatti, I found new case where we haven't autocomplete: 
- adminhtml/system_config_source_store
