### ISSUE TITLE
Quit nagging about XML line wrap

### ISSUE THREAD

**Issue by ScreamingDev** [enriquepiatti/Magicento#107]
Please give the possibility to suppress error messages from Magicento.
Especially remembering that wrapped XML lines are not that good for Magento is anoying, as you want 'em in other projects.

**Comment by enriquepiatti** [comment]
@sourcerer-mike that warning should be shown only if you have Magicento enabled for your project. And normally Magicento can detects if the current project is not a Magento project and disable itself).
Is one of those things not working for you? I mean:
a) you have disabled Magicento but it still showing the error
b) it is not a Magento project but Magicento continues enabling itself (try removing .idea/magicento.xml and restart the project, Magicento should be disabled).

**Comment by ScreamingDev** [comment]
I take a bit of b) with c)

It is a mixture oft WordPress, Magento and node.JS

yep, odd mixture but if one depends in the other then you want to see all in one.

**Comment by enriquepiatti** [comment]
hmmm... so you want to maintain Magicento enabled while working with code from node.JS and WordPress and also you want to use wrap text? 
Anyway, Magicento should show you the warning just one time (probably when you start the project or you enable Magicento on it). It normally will show the warning every time you autocomplete some XML, but only if the autocomplete is related with Magento.
When are you getting  the warning? it is shown too often?

**Comment by ScreamingDev** [comment]
I don't want to disable the option Magicento is warning about, while working with Magento config.xml (e.g.) because I like to have that for the other.
So yes, it is there all the time I work with magento. When I use xml of the other I disable Magicento.

**Comment by enriquepiatti** [comment]
OK, I will add an option to disable all the Magicento notification, but be careful with that, the reason why I've added that warning is because Magicento could be adding nodes for you without noting it (generating events, modules, rewrites, etc) and if you have that option enabled then PHPStorm could be wrapping some node and breaking your XML, and you won't note it so easily because everything is happening "behind the scenes".

**Comment by ScreamingDev** [comment]
That's okay, especially when it is suppress for a project instead of deactivated for ever.
More general this could affect every alert from the extension - to "suppress for this project" besides the "Ok" button.

I like that!
Special thanks!

**Comment by enriquepiatti** [comment]
Added a config option for bypassing messages in v2.7
