### ISSUE TITLE
Error flushing the cache

### ISSUE THREAD

**Issue by kidonchu** [enriquepiatti/Magicento#109]
I am using Windows 8.1, PhpStorm 7.1.3, Magicento 2.6.5.
When I do following actions, I get "Error flushing the cache" notification.
- Add @method PHP Doc
- Flushing the cache
  What's causing this issue?

**Comment by enriquepiatti** [comment]
Hi @kidonchu, are you getting "Error flushing the cache" when you are using Add @method too?  
Anyway, are you sure the PHP features are working fine with your project? Please go to Magicento Settings and press the "Test PHP" button.  
If the test works fine, please choose the HTTP option for PHP (if you don't have it already) and configure it for your Magento, press test again.
If everything it's OK there, check the eval.php in your Magento server, try executing it manually to see the result.

**Comment by kidonchu** [comment]
Thanks for your step by step solutions. It flushes the cache without any error message now. I was using a vagrant box with virtual host setup inside, and I didn't configure path to eval.php correctly. Thank you!
