### ISSUE TITLE
Hotkey Bindings

### ISSUE THREAD

**Issue by nhp** [enriquepiatti/Magicento#11]
Is there any possibility to allow rebinding of the hotkeys, because middleclick is bad for *nix users and ctrl+b is also used, at least for me (IdeaVim and behavior from vim in general) .
Would be lovely to change the bindings.

**Comment by enriquepiatti** [comment]
Hi nhp, how are you using the feature "Go to..." in PHPStorm then? the hotkey you are using for that should work for magicento too (Ctrl+B and middle click are the default in PHPStorm).
Let me know if it works (or not...)

**Comment by nhp** [comment]
ah.. using ALT+F3 for "Go to declaration" very nice, works like a charm now.

**Comment by enriquepiatti** [comment]
Just as an extra note: 
Magicento has only **one** shortcut: Alt+M (Option+M), and it's context aware, that is, it will show different options depending on where is the cursor (over a $var, inside a .phtml, inside a script installer, etc etc).
The other features are extensions of the normal features of PHPStorm (Ctrl+Space, Ctrl+B etc).
You can see a video with almost all the features here: 
https://www.youtube.com/watch?v=r0kDf9McW9o
