### ISSUE TITLE
Magicento 2.6.5 on PHPStorm 7.1.3 not installing

### ISSUE THREAD

**Issue by AcousticRand** [enriquepiatti/Magicento#111]
Windows 7 pro, PhpStorm 7.1.3 PS-133.982

I can't update via Plugin Manager, I keep getting:
Fail to load plugin descriptor from file magicento.jar

**Comment by enriquepiatti** [comment]
Hi @AcousticRand this is normally due a corrupt .jar file, please send me an email so I can check your user and send you the download link again.

**Comment by enriquepiatti** [comment]
@AcousticRand don't put your private information here, is a public forum, send me an email to contacto@enriquepiatti.com

**Comment by AcousticRand** [comment]
The new download link you sent me worked.  Thank you
