### ISSUE TITLE
Enable Alt+M Magicento options in project window

### ISSUE THREAD

**Issue by kidonchu** [enriquepiatti/Magicento#112]
This is more of suggestion for a feature. 
I tried creating a module from the project tree panel without opening any file. It seems that Magicento options do not show up in this panel. In order to create a module, I have to open at least one file, place my cursor on the editor window, press Alt+M, and then select Create module option.
Is it possible to show Magicento options without having my cursor on editor window?

**Comment by enriquepiatti** [comment]
Done in v2.7
