### ISSUE TITLE
Automatic factory class type recognition : autocompletion not working

### ISSUE THREAD

**Issue by theredled** [enriquepiatti/Magicento#114]
Hi,

I'm using PHPStorm 6.0 on OS X 10.9, and automatic factory class type recognition doesn't work. 
To be accurate :
- It works when you cmd/click on a 'module/class_path' string, it goes to the right class.
- It doesn't work for autocompletion : the recognized class is Mage_Core_Model_Abstract for getModel.

Anything wrong with my configuration ? 
Thanks

**Comment by theredled** [comment]
Addentum : autocompletion doesn't work either in templates (block/template declared in xml layout)

**Comment by enriquepiatti** [comment]
@theredled you need at least 6.0.3 if I right remember for those features, anyway PhpStorm 6 is really old, the last version is 7.1.3, you should really upgrade it. Or if your PhpStorm license is expired and you don't want to buy another one please at least update to the last 6.x available (minor upgrades are free with PhpStorm).

**Comment by theredled** [comment]
All right it works now with 6.0.3 !
Great extension, big time saver !
