### ISSUE TITLE
MagicentoScripts - Broken

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#118]
In latest Magicento version (2.6.5) I haven't any scripts in Magicento.com section. 
Right click(to refresh) on Magicento.com isn't working.
![image](https://f.cloud.github.com/assets/1873745/2343621/7e567876-a511-11e3-948b-a8530662d756.png)

**Comment by enriquepiatti** [comment]
The scripts under "Magicento.com" are requested from magicento.com (wow! ^_^), sometimes the server could be down or not responding correctly. Is this problem still happening? if yes, it occurs in all your projects?

**Comment by ihor-sviziev** [comment]
@enriquepiatti yes, it still happening and occurs in all projects.

**Comment by enriquepiatti** [comment]
Hi @igor-svizev I've sent you a new version to your email, please install that and check if works now.
Regards!

**Comment by Keloran** [comment]
same problem

**Comment by enriquepiatti** [comment]
Hi @Keloran I have sent the new version to you too. Please check your email.

**Comment by Keloran** [comment]
@enriquepiatti that worked thanks

**Comment by ihor-sviziev** [comment]
@enriquepiatti I checked too, now this issue isn't reproduce.
Thanks!
