### ISSUE TITLE
Crashes in phpStorm 5 in layout xml files when "enable php execution" option is enabled

### ISSUE THREAD

**Issue by utagaiby** [enriquepiatti/Magicento#12]
PHP Storm Crashes when I try to edit layout xml files and Magicento tries to suggest me page xml tag. If I disable "php execution" option in Magicento settings and try to write layout xml file, Magicento instanty shows me error that "This feachure is available only with Php Enabled at this moment" and when I pres "OK" and type next character Magicento shows me this message again. 
I use windows 7 with deployment of project to Ubuntu server, think this might be important because one time I captured PDO error with Magicento in layout xml file and "php execution" enabled.

**Comment by enriquepiatti** [comment]
mmm... so your local server is on a Virtual Machine? if that's the case, do you have symlinks between your local files in Win7 and the files in your VM? 
Try using the HTTP option when you enable PHP, and put your local domain (anyway this will only work if you have symlinks I guess).
Also, try to use the "Evaluate In Magento" feature (Alt+M), type anything there, like "5+3" you should see "int 8".
Lastly, if you have another local project (not with a VM) try to run the PHP features there to see if that's the problem.
Let me know how it goes please.

Thanks !

**Comment by joshdavenport** [comment]
I'm getting a very similar issue on Mac OSX 10.6.8. No symlinks.
The evaluate feature works as expected so everything is fine there, the only issues I have are with layout XML.
Have to turn off Magicento completely to be able to edit layout XML files without an instant crash, can't just turn off PHP execution as you are presented with "This feachure is available only with Php Enabled at this moment".
The ability to turn off XML suggestion would be preferable!!

**Comment by enriquepiatti** [comment]
Yes, this was a bug, it's fixed now, I need to upload the new release (I hope to do that in these days, I was really busy sorry :( )
Momentarily you need to disable Magicento when editing layout files, because autocomplete is executed automatically by the IDE everytime you wrote a character.

**Comment by enriquepiatti** [comment]
This should be fixed in v0.9.7.
The layout features are not ready yet, it's a temporary release for solving this issue because it was blocking the IDE.
