### ISSUE TITLE
Can't upgrade from 2.6.5 to 2.7 magicento plugin

### ISSUE THREAD

**Issue by northdakota** [enriquepiatti/Magicento#126]
Sbj:
I can't upgrade from 2.6.5 to 2.7 magicento plugin - upgrade button was not showing for me. so my temp solution:
install old version 2.6 and this magicento version propose me to update to 2.7

P.S. Sorry for my bad english.

**Comment by enriquepiatti** [comment]
Hi @northdakota yes I think there was an error in version 2.6.5, anyway, for the next time, you don't need to install an old version to get the update, you can use your private link, it will download the lastest Magicento version, always.
Also, if you want to make sure you are notified when a new Magicento version is released, please follow @magicentoplugin on twitter, I'm putting the updates there too.
I'm working on a new version so pay attention ;)
