### ISSUE TITLE
Multiple Definitions and Multiple Declarations warnings.

### ISSUE THREAD

**Issue by Petce** [enriquepiatti/Magicento#127]
New to PHPStorm and Magicento. 

However, after setting everything up with Magicento, it appears that PHPStorm is telling me that all my classes even the core ones, have multiple declarations and multiple definitions.

Help would be appreciated.

**Comment by enriquepiatti** [comment]
Are you sure that's a Magicento problem? what happens if you disable Magicento? try with a new Magento project too and let me know please.

**Comment by dancetrain** [comment]
It can be problem with magento compiler, which merge classes into includable files and saves it to includes/src

Try to exclude this directory from project here
Project Settings -> Directories

**Comment by Petce** [comment]
That was it dancetrain, thank you very much. I don't understand why this folder has files in it, the compiler is disabled on my system...

**Comment by enriquepiatti** [comment]
good catch @dancetrain, thanks ! closing this
