### ISSUE TITLE
Path to Mage.php is not valid: null

### ISSUE THREAD

**Issue by kesonno** [enriquepiatti/Magicento#13]
Hi, after the update to 0.9 version every time I save a file appear a notify message saying "Path to Mage.php is not valid: null".

My setup: OSX 10.7.4, PhpStorm 5.0.2.

**Comment by kzulis** [comment]
Same here! After update getting the same message: 'Path to Mage.php is not valid: null'

Setup: Windows 7, PHPStorm 4.0.3

**Comment by enriquepiatti** [comment]
Please check the Path to Mage.php on File > Settings > Magicento.
You can see a video here (it's useful to see all the features too):
http://www.youtube.com/watch?v=r0kDf9McW9o
Let me know if that solves the problem.

**Comment by kzulis** [comment]
Thanks, it works now.

**Comment by kesonno** [comment]
Confirmed, it works!

Thanks!
