### ISSUE TITLE
Having issues using Create Model Triad

### ISSUE THREAD

**Issue by DrewKolstad** [enriquepiatti/Magicento#144]
I'm getting a "IncorrectOperationException: Element cannot be added" error in the Event Log.

The only thing that gets added to the config file is the following...

``` xml
<models>
    <my_module>
        <class></class>
    </my_module>
</models>
```

Please advise what I should do to resolve this.

**Comment by enriquepiatti** [comment]
Hi @drewk289 could you add more information about this? is still happening? which Magicento version are you using? have you tried with another Magento project?

**Comment by nebojsanovic** [comment]
Hi, same issue for me. Any solutions or suggestions?

**Comment by enriquepiatti** [comment]
@nebojsanovic this is really old, when are you getting that error? please describe the steps to reproduce it and also let me know your PhpStorm and Magicento version

**Comment by nebojsanovic** [comment]
Apologize , I have used wrong model name.
