### ISSUE TITLE
PHP Setting not saved correctly

### ISSUE THREAD

**Issue by mhodge13** [enriquepiatti/Magicento#145]
I recently started having an issue where the php setting of magicento is not saving correctly.

If I go to phpstorm preferences menu and select magicento->Use PHP Interpreter and click the apply button and then ok, it appears to have saved.  But when I try to flush cache from the magicento menu it shows an error messagin stating "Error flushing the cache".  When I go back to preferences and select Magicento it seems the PHP setting changed back to the "Use HTTP" setting.

Saved the php setting
http://screencast.com/t/LHpwR059

Tried flushing cache
http://screencast.com/t/xb0LrGbyu

Back to preferences
http://screencast.com/t/F2tVHiVk4LXi

Anyone else noticing this?

**Comment by enriquepiatti** [comment]
Hi @mhodge13 I can reproduce it too so yes, it's a bug.
Anyway, is it working fine the PHP Interpreter option for you? I was even thinking in removing that option (http is now the default one) because is not working for most of the users, and the http works in almost every situation (even using virtual machines, and you could also use it with remote servers if you do some tricks).

**Comment by mhodge13** [comment]
Enrique

When does the eval.php script get added?  I do not see it being added and I
get a 500 error when trying to flush the cache since the eval.php script is
not available.

On Wed, Dec 10, 2014 at 10:35 AM, Enrique Piatti notifications@github.com
wrote:

> Hi @mhodge13 https://github.com/mhodge13 I can reproduce it too so yes,
> it's a bug.
> Anyway, is it working fine the PHP Interpreter option for you? I was even
> thinking in removing that option (http is now the default one) because is
> not working for most of the users, and the http works in almost every
> situation (even using virtual machines, and you could also use it with
> remote servers if you do some tricks).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/enriquepiatti/Magicento/issues/145#issuecomment-66480254
> .

## 

_Name: Mark Hodge_ _Senior Application Engineer - Magento Certified
Developer PLUS+_

_P:_ 815.316.6363 *F: *312.564.3150 *S: *mhodge.lcg

mhodge@lyonscg.com

**Comment by enriquepiatti** [comment]
try searching for "eval.php" in PhpStorm, also read the full settings in Magicento, is explained how the eval.php works. Maybe is not accessible from HTTP in your local server/magento config.
By default it is created inisde .idea/magicento/eval.php so you should access to it using:
http://www.yourlocalmagentoserver.com/.idea/magicento/eval.php
And if you choose to save it inside "var" folder:
http://www.yourlocalmagentoserver.com/var/magicento/eval.php

you don't need to do that, only if you want to debug the eval.php, magicento will execute that internally, but you need to make sure those URLs are accesible.

**Comment by mhodge13** [comment]
Enrique

I was able to find the file and the eval.php did the trick.  You can close
this ticket.

Thank you for your quick help.

On Wed, Dec 10, 2014 at 1:44 PM, Enrique Piatti notifications@github.com
wrote:

> try searching for "eval.php" in PhpStorm, also read the full settings in
> Magicento, is explained how the eval.php works. Maybe is not accessible
> from HTTP in your local server/magento config.
> By default it is created inisde .idea/magicento/eval.php so you should
> access to it using:
> http://www.yourlocalmagentoserver.com/.idea/magicento/eval.php
> And if you choose to save it inside "var" folder:
> http://www.yourlocalmagentoserver.com/var/magicento/eval.php
> (you don't need to do that, only if you want to debug the eval.php,
> magicento will execute that internally)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/enriquepiatti/Magicento/issues/145#issuecomment-66511019
> .

## 

_Name: Mark Hodge_ _Senior Application Engineer - Magento Certified
Developer PLUS+_

_P:_ 815.316.6363 *F: *312.564.3150 *S: *mhodge.lcg

mhodge@lyonscg.com
