### ISSUE TITLE
Make compliant with modern project structure

### ISSUE THREAD

**Issue by Seb2nim** [enriquepiatti/Magicento#146]
Can you please take a look at this project structure and consider evolve plugin to be compatible :

https://github.com/AOEpeople/Magento_SampleProject

**Comment by enriquepiatti** [comment]
Hi @Seb2nim, Could you add more information about this, what features from Magicento are not working and what is the final folder structure?
Magicento can manage multiple Magento paths (normally used for example with modman), it just has one limitation, your folder structure needs to mimic always the normal Magento folder structure, that is, you need to have "app/code/", "app/etc/" etc.
Check "New Features in 2.8.6":
http://magicento.com/#magento-paths

**Comment by Seb2nim** [comment]
Hi,

Actually, the idea behind this project structure from Fabrizio is using vanilla magento + composer + modman

if you setup this project in phpstorm, you just have to run ‘install.sh’ script to setup.

-> Magento will be downloaded and installed in htdocs.

-> .modman folder will be created

modman folder is supposed to receive :
- dependencies (magento modules) defined in composer.json : retreived from remote drepositories
- hold ‘custom’ modules : modman modules : theme for example

What actually didn’t work with magicento is this the "new module" wizard : new module is always added in htdocs’s structure.

I want to define my new module as a subfolder of .modman folder

**Comment by enriquepiatti** [comment]
Please read about the feature I mention @Seb2nim is a godd idea to read all the features too, I'm pretty sure you are using only 20% of what Magicento can do (it's just a statistic fact because nobody reads the docs :) I think you will discover something useful if you do it)
Let me know if that feature is not working well in your case.
