### ISSUE TITLE
IllegalDataException

### ISSUE THREAD

**Issue by Srikanth-AD** [enriquepiatti/Magicento#147]
![screen shot 2014-12-31 at 3 15 40 pm](https://cloud.githubusercontent.com/assets/915560/5590320/04e57d08-9100-11e4-869f-ac33862756a7.png)

Items marked in red don't result in any further prompts and Event log has the same error specified above.
![screen shot 2014-12-31 at 3 54 23 pm](https://cloud.githubusercontent.com/assets/915560/5590535/8dbb592c-9105-11e4-8aeb-782973fca43a.png)

Set store does bring up the prompt with store codes but it doesn't actually set the store in magento.

I am using PHPStorm 8.0.2 on a Mac OS X.

**Comment by enriquepiatti** [comment]
Set store is used internally, for evaluating code in Magento, not for setting anything in Magento.
Regarding to the IllegalDataException I think I'm going to need more details, it seems to be related with some malformed xml, check your Magento xml files, try refreshing Magicento Cache (ALT+M > Clear Magicento Cache) and test with a clean Magento project too (without any extra modules)

**Comment by Srikanth-AD** [comment]
I thought the set store feature was to set the store id/code to be used globally. 
Example code:, this can be set in index.php

```
$store_id = '<number goes here>';
$mageRunCode = '<storecode goes here>';
$mageRunType = 'store';

Mage::app()->setCurrentStore($store_id);
Mage::run($mageRunCode, $mageRunType);
```

I will check the xml files...

**Comment by enriquepiatti** [comment]
You can create a Magicento PHP Script to do that:
http://magicento.com/#magicento-php-scripts

**Comment by Srikanth-AD** [comment]
You were mostly right about malformed XML. 
The issue was in a module's config.xml which contained nested CDATA tags. Turns out you can't nest CDATA tags. refer: http://en.wikipedia.org/wiki/CDATA#Nesting

PHPStorm doesn't complain about this though.

Thanks!
