### ISSUE TITLE
app/Mage.php is not found for modman based project.

### ISSUE THREAD

**Issue by IvanChepurnyi** [enriquepiatti/Magicento#15]
If you develop an extension that is supposed to be a module that can be easily integrated with [modman](https://github.com/colinmollenhour/modman), Magicento always throws warning that Mage.php is not found, however some basic Magento version is placed in include path. 

As far as I see, this can be fixed by modifying method to support looking for a file path in the following lines:
https://github.com/epiattisumma/Magicento/blob/master/src/com/magicento/MagicentoSettings.java#L193

**Comment by Vinai** [comment]
I believe this has been fixed in the meantime - at least it works fine for me.

**Comment by enriquepiatti** [comment]
Currently you can set the path to Mage.php to a different folder (not included in the project folder).
Magicento will create the new content on the project folder anyway, but the autocomplete etc will works as always (if you have the Magento source added as an external library or somewhere available for PhpStorm).
But you need to use the normal Magento structure in your project, I mean you need to have for example:
[PROJECT]/app/code/local/...
not just something link:
[PROJECT]/local/ 
(even when modman allows it)
And also if you want to use the Magicento features which requires PHP interaction (flush cache, evaluate in Magento, etc) you need to make sure your deploy settings are correctly configured.

Please re open if you find more problems or you think it would be good to add some enhancements here.
Thanks !
