### ISSUE TITLE
Autocompletion adds wrong apostrophes ( ' )

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#150]
```
$orders = Mage::getResourceModel('sales/order_col');
```

autocompletes to

```
$orders = Mage::getResourceModel(''sales/order_collection''); // see the two '' in front and end!
```

Using PHPStorm 8.0.3 (139.1069) on Mac OS X 10.9.5

**Comment by enriquepiatti** [comment]
Not happening to me, but I was testing with 8.0.2 on Windows.
I will try with 8.0.3 later
Can you try the autocomplete without the quotes?

$orders = Mage::getResourceModel([CTRL+SPACE]);
or
$orders = Mage::getResourceModel(sales/order_col[CTRL+SPACE]);

**Comment by Schrank** [comment]
```
$orders = Mage::getResourceModel([CTRL+SPACE]); 
```

works as expected :+1:, takes a while to load the list, don't know why.

```
$orders = Mage::getResourceModel(sales/order_col[CTRL+SPACE]);
```

doesn't work. But it works until `sales`, when I add the `/` it feels like the context is lost. If I write `order_col` it is no longer autocompleted, but when I delete everything up to the o it is autocompleted with `oauth/...` so the `sales` is missing in this context

**Comment by mvenghaus** [comment]
I have the same issue when I start autocomplete wihtin quotes .. wihout no problems. (8.0.3 and 9 EAP - Windows 8.1)

**Comment by enriquepiatti** [comment]
Yes, this is a problem with 8.0.3+ 
It's already fixed in the new Magicento version (will be released soon)

**Comment by dseibert9** [comment]
I hate to be a pest but this issue is REALLY irritating.  Any chance that new version is coming out soon?  If the new version isn't ready, can you patch the current version with this fix?

**Comment by enriquepiatti** [comment]
Hi @dseibert9 yes, please send me an email and I will compile a special version with that fix for you

**Comment by lfalkenhain** [comment]
Hi @enriquepiatti,

are there any plans to release the fix for that in the next time? 
This behavior irritates and stops me in my workflow. Problem is occuring in 8.0.3 and 9.0.x EAP versions of phpstorm. 

Thanks

**Comment by enriquepiatti** [comment]
Hi @lfalkenhain please contact me by email and I will send you a special version with the fix (anyone else needing this fix right now please contact me too)

**Comment by elvetemedve** [comment]
Hi @enriquepiatti,
I just wanted to note that this problem is still happening with v2.9.0 and PHPStorm 9.0.

**Comment by dhargitai** [comment]
Hi @enriquepiatti,
The problem also exists at me in v2.9.0 and PHPStorm 9.0, on MacOS.

**Comment by enriquepiatti** [comment]
The version with the fix is v.2.9.1+ is not officially released (new users have this already), but if you need the fix please send me an email with your private link (or your username) and I will send you the fixed version

**Comment by Bogardo** [comment]
I'm still having issues with this.
Currently running:
Windows 8.1
PHPStorm 10.0
Magicento 2.9.0

**Comment by Schrank** [comment]
Might be, because you are not 2.9.1+ ;-)
