### ISSUE TITLE
Having an issue creating a Grid and Form

### ISSUE THREAD

**Issue by csduncan** [enriquepiatti/Magicento#152]
Model setup and configured properly. Even tested a instantiation:

![create_grid_and_form_and_model_instance_php_-_clientinfo_-___volumes_storage_sites_clientinfo__and_local-clientinfo_gemshelp_com_clientinfo_test__and_skype](https://www.evernote.com/shard/s13/sh/3f7468df-2daa-443a-86ba-ebc2e6e6670a/6e00689fb036d903b50ae969911cec46/deep/0/Create-Grid-and-Form-and-Model-Instance.php---clientinfo-----Volumes-Storage-Sites-clientinfo--and-local-clientinfo.gemshelp.com-clientinfo-test--and-Skype.png)

However, create Grid and Form function cannot find model class for it? Am I missing something or is this an actual bug?

**Comment by enriquepiatti** [comment]
Are you sure there isn't any typo or camel case error somewhere? your var_dump is showing "gorilla_clientinfo/module" not "gorilla_clientinfo/instance".
Have you tried refreshing Magicento cache (ATL+M > Clear Magicento Cache)
Have you tried using the factory instead the model class name? (gorilla_clientinfo/instance instead of Gorilla_Clientinfo_Model_Instance)

**Comment by csduncan** [comment]
Ah, right you are--I was var_dump - ing the wrong entity. However, both the instance and module entities are pretty much the same. Here's the same test with the module entity this time through and through.

![create_grid_and_form_and_model_module_php_-_clientinfo_-___volumes_storage_sites_clientinfo__and_local-clientinfo_gemshelp_com_clientinfo_test_](https://www.evernote.com/shard/s13/sh/4f9ea64b-0c17-45bf-88e1-ae8b8cd3d0fc/5b4b2315eb141b7bdfc6cce1f94b48f6/deep/0/Create-Grid-and-Form-and-Model-Module.php---clientinfo-----Volumes-Storage-Sites-clientinfo--and-local-clientinfo.gemshelp.com-clientinfo-test-.png)

I also tried clearing the Magicento cache and got the same result. Still doesn't think that classname for the model is valid--even though I can clear instantiate it using the factory reference. I will also say that the value in that "Model" field is the one auto-inserted because I utilized the Magicento menu from within the Model class.

**Comment by enriquepiatti** [comment]
Could you do these tests too?
a) When you use Ctrl+N to find a class and type Gorilla_Clientinfo_Model_Module there, is PhpStorm finding that class?

b) When you use somewhere in your code:
Mage::getModel('gorilla_clientinfo/module')
is Magicento giving you the correct autocomplete and also the correct GoTo (Ctrl+B when the cursor is over the factory string).

c) is Magicento offering autocomplete hints for the factory string (specifically for gorilla_clientinfo/module)?
Mage::getModel(CTRL+SPACE HERE);

d) Is that the only class/module that is not working?

**Comment by csduncan** [comment]
Sure thing. Here's what I found:

a) Looks like it's finding two copies of the class (I have the checked-out code and a symlinked folder both in my project folder). However, once I choose either of them, it appears to navigate to the correct class file.
![image 1](https://www.evernote.com/shard/s13/sh/fab69e6f-315a-4294-8196-45925823ff11/9a7823a0f62168cd4b3287cbfba50a54/deep/0/Model-Module.php---clientinfo-----Volumes-Storage-Sites-clientinfo-.png)

b) The autocomplete appears to be working (at least displaying methods from Mage_Core_Model_Abstract...no custom methods from my class though). Also, the GoTo prompts me (as usually happens) to select which of the copies of the file in my project folder I'd like to navigate to (because of the aforementioned symlinking I do in my project folders for vagrant's sake).
![image 2](https://www.evernote.com/shard/s13/sh/12dba739-4c0d-4af8-8eac-9ad1c94c01f4/63f6fb24b85a9459a2c1649dbb85792e/deep/0/Module-Grid.php---clientinfo-----Volumes-Storage-Sites-clientinfo-.png)
![image 3](https://www.evernote.com/shard/s13/sh/ba351815-6820-469a-91cb-f3c70e812dae/0988206c98181b99736a7022fbe4e887/deep/0/Module-Grid.php---clientinfo-----Volumes-Storage-Sites-clientinfo-.png)

c) Appears to be.
![image 4](https://www.evernote.com/shard/s13/sh/70ddf5c8-ffd2-4fa7-a248-422d519ff799/96d6592b959dceb3ff4121d751d8bc86/deep/0/Module-Grid.php---clientinfo-----Volumes-Storage-Sites-clientinfo-.png)

d) No, I tried several custom classes. It appears to be affecting my entire project (haven't had a chance to try on another project though).

Knowing next to nothing about PhpStorm extension-writing, I have a feeling the "duplicate" code folders within my project might be what's tripping things up. Seems the most likely common thread--but again knowing next to nothing about storm plugin development. Thanks again for your help troubleshooting this. Would love this feature to work for me as it would cut loads off my typical build times for grids/forms.

Let me know if you want me to try anything else.

**Comment by enriquepiatti** [comment]
Yes I guess that's the problem too, why you have both classes in your project, is not any way to avoid that in your PhpStorm project, it will work much better in general (not only Magicento, that thing is consufins PhpStorm too...)

**Comment by csduncan** [comment]
Yeah, if that's the issue, then IMHO I'd say this could be a potential feature addition then. Might even be able to argue it steps into bug territory since Phpstorm handles it quite well (let's you pick which file you want) and your plugin is supposedly extending storm, right? _wink wink_

While I could rework my workflow to only have one copy of the code in my project, I'd wager that I'm not an exception to the rule here (which is why I'd vote for a fix/feature addition here rather than a change in approach). Working on projects for long periods of time can often lead to code in various places (mostly for archival or branch organization). 

Let me know if there's any more information I can provide as you explore this topic. I don't know level of effort to make this change, but I'm probably not the only one exposed to it.

**Comment by enriquepiatti** [comment]
Hi Chris, sure, could you send me an email with more details about how you have configured your project? I will try to see what is the problem and if it can be fixed.
But again, maybe you are doing that for some good reason, but even when PhpStorm is managing it correctly, you can see it finds two definitions for every class, and everytime you need to access a file is slower, not only because in general PhpStorm will run slower (maybe your machine can manage it pretty well anyway) but also because you need to choose manually which file do you want.
I think is possible to ignore some folder in PhpStorm so it is not read for searching classes etc, could that be another solution for you? or you want to keep the 2 files and classes in your PhpStorm project for some reason (I'm not understanding very well this part)

**Comment by chrisduncan** [comment]
Sure. I'll send you an email with details on the project configuration. I also looked into ignoring the folders. It looks like you can do it for git/subversion purposes, but nothing where storm actually ignores files.

**Comment by csduncan** [comment]
Good news! Your last message gave me an idea. I tried narrowing the scope of my project (to the folder directly containing my code) and that seemed to fix this issue (Was able to create the Grid and Form!). So if anyone else runs into this, this is a workaround. 

I think the situation that caused this was having my code folder and then a symlink to that folder (I use this symlink folder for vagrant so I can swap code folders/branch folders around and not have to change any vagrant configuration settings--just have to point the symlink to a new folder). This caused a condition where storm thought I had two folders with identical code in them--so needed my input when I asked to GoTo, or in this case use the Magicento Create Grid and Form functionality.

You can see it for yourself if you setup your code folder something like this:

{project_folder} (Open in PHP Storm)
- httpdocs/ (code folder)
- local.clientdomain.com@ -> httpdocs/ (symlinked folder)

I created the above situation by simply:
 ln -s local.clientdomain.com/ httpdocs

Again though, this is a workflow change, but ideal would be to allow for Magicento to allow workflow like this as well (some sort of file-chooser like storm allows).

**Comment by csduncan** [comment]
Also, might be good to warn others of this. Unless I'm the only one :P

**Comment by enriquepiatti** [comment]
I think the workaround is good enough, because is much better to have a good your project in PhpStorm configured correctly even if you are not using Magicento. I mean there isn't any good reason (I think) to have the code twice in PhpStorm, you can always create a project with the correct root.

I will close this but anyway, thanks to your your explanation I think this post will be useful to anybody searching or having a similar issue.

**Comment by mokadev** [comment]
Hi,
thx @chrisduncan , the same problem occured with modman , i have to exclude the .modman folder to enjoy this Magicento functionnality
