### ISSUE TITLE
Getting invalid variable name suggestions when Magicento is active

### ISSUE THREAD

**Issue by MarcusDalgren** [enriquepiatti/Magicento#157]
Running on PHPStorm 8.0.3 and Magicento 2.9.1. I've been trying to use it during the last couple of days because of the great features but when I'm editing phtml files PHPStorm doesn't resolve variable names properly in the auto suggest.

After awhile pretty much all I get is a list of suggestions where every item says Invalid. Turning it off and then reactivating the plugin seems to reset this behavior but it returns again pretty quickly. A quick fix for this would be nice since it's really making the plugin hard to work with.

**Comment by enriquepiatti** [comment]
Hi @MarcusDalgren, I think I couldn't understand the problem, and the temporary solution is really weird too, could you provide some screenshots?
Are you sure there isn't any conflict with another plugin?
Also, have you tried the same in a clean magento installation (without any extra modules, modman etc, and using the project folder in phpstorm as the project root from that Magento)?
