### ISSUE TITLE
Better magicentoinstaller template

### ISSUE THREAD

**Issue by chadrien** [enriquepiatti/Magicento#162]
Hey, for now when creating a magicentoinstaller we're asked for `installer`, `this` and `installer-` variables. This is because the template is written is "plain PHP" so for the intellij parser `$installer` is a template variable.
To simply render `$installer` you have to put `${DS}installer` in the template.

Here are the changes I've made:

```
<?php
#parse("PHP File Header")

try {
    /* @var ${DS}installer Mage_Core_Model_Resource_Setup */
    ${DS}installer = ${DS}this;
    ${DS}installer->startSetup();



    ${DS}installer->endSetup();
} catch (Exception ${DS}e) {
    Mage::log(${DS}e->getMessage());
}
```

With this, I'm now only asked for the template name.

**Comment by enriquepiatti** [comment]
Hi @chadrien but when you create that installer using the "Create Module" action does it work fine? Because the template was designed for that, not to be used standalone

**Comment by chadrien** [comment]
Lucky me, it does work with the `Create Module` action! (I never use this action and usually use this template standalone :stuck_out_tongue_winking_eye: )
