### ISSUE TITLE
"Path to Magento to use for new files" doesnt get saved.

### ISSUE THREAD

**Issue by pquerner** [enriquepiatti/Magicento#168]
Whatever I put into the field, even if its bogus (empty string, cmd.exe or whatever) doesnt get saved. The next time I open up the settings menu, the same old value is present.
Which I do not want.

PHPstorm 8.0.3
Magicento 2.9.0

**Comment by pquerner** [comment]
I've deleted the default settings directly from one of phpstorms config files (~/config/options/project.default.xml)
Lets see whats changed

**Comment by enriquepiatti** [comment]
Make sure you are accessing to the project settings and not default phpstorm settings.
Let me know if the problem persists

**Comment by pquerner** [comment]
This does not help @enriquepiatti as I am openeing the `project settings` menu.
