### ISSUE TITLE
Logic for detecting Mage.php

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#17]
Why do we have to specify Mage.php manually?
What are the challenges to do so automatically?

https://github.com/netz98/n98-magerun also is able to find the magento root - maybe the same logic can be used here?

**Comment by enriquepiatti** [comment]
Actually it should detect the path, in my case it always works. Can you try creating a new Magento project and tell me what happens?
And if it doesn't work, please tell me what OS and PHPStorm version you are using.

**Comment by amenk** [comment]
Ubuntu Precise, latest PHPStorm EAP, I just opened an existing Magento project (via Open Directory!) and it tells me it did not find the Mage.php. The project root path I open is identical with the Magneto root.

**Comment by enriquepiatti** [comment]
If you opened the same project before with an older version of Magicento probably the settings are corrupted. If that's the case could you try to create a new clean project?
Anyway this is something related with the IDE, right now the plugin is using 3 methods for detecting the path, and it works for me but I know there are users having problems with this (maybe is the OS because I'm using Windows)

**Comment by amenk** [comment]
Same with a project that does not yet contain an .idea folder

**Comment by enriquepiatti** [comment]
amenk, I think I found something that could be causing the problem, do you want to add me to skype (enriquepiatti) so I can send you a modified version of magicento for testing it?

**Comment by amenk** [comment]
Okay. You could also upload it as a separate branch here on github

**Comment by benmarks** [comment]
Happening for me as well on my Mac 10.7, just installed Magicento.

**Comment by enriquepiatti** [comment]
This is currently fixed (I hope), will be available on the next relase.
I will upload it this weekend, if you have installed the lugin directly from the repository (like is shown here http://www.youtube.com/watch?v=r0kDf9McW9o ) you will get a notification from the IDE.

**Comment by benmarks** [comment]
Fantastic. It's an exciting new topic in the Magento U development classes.

**Comment by enriquepiatti** [comment]
This should work fine in v0.9.7. Please reopen if it's not.
Thanks !
