### ISSUE TITLE
Creates module in wrong project

### ISSUE THREAD

**Issue by kandrejevs** [enriquepiatti/Magicento#170]
When working on multiple projects, magicento will create module in other project and get dependency multi select from wrong project.

**Comment by enriquepiatti** [comment]
Hi @pankijs, what do you mean working on multiple projects? do you mean opening multiple projects in PhpStorm at the same time?

**Comment by kandrejevs** [comment]
No, just having multiple projects on localhost. for example, I work 4 hours on one, then switch to other, if I  use auto module creation, sometimes module files are added to first project..

**Comment by enriquepiatti** [comment]
but you are closing the first project and opening another one, or you have both projects opened in PhpStorm (two windows)?

**Comment by pluckrose** [comment]
I also have this problem, even if the project in question is not open. No matter which project I open it does always seem to relate back to this one project.

When I create a module for instance, inside sites/x10 it actually creates it inside sites/x2

weeiirrddd

**Comment by enriquepiatti** [comment]
@pluckrose please check your Magicento settings (make sure you are editing the project settings not the default settings, in Mac this is confusing, never edit Magicento settings with the default settings).
https://www.jetbrains.com/phpstorm/help/accessing-settings.html
Make sure you all your Magento paths are correct there
