### ISSUE TITLE
Cyclic component initialization: com.magicento.MagicentoProjectComponent [Plugin: Magicento]

### ISSUE THREAD

**Issue by hgati** [enriquepiatti/Magicento#172]
![snap1](https://cloud.githubusercontent.com/assets/6913728/8817483/bcd543f4-306e-11e5-83de-6804d31d23a8.png)

What is this?

**Comment by enriquepiatti** [comment]
Hi @hgati could you provide more information? what version of PHpStorm, Magicento and OS are you using?
Are you opening multiple projects at the same time?
Is this happening all the time and blocking the IDE or Magicento functionalities?

**Comment by hgati** [comment]
currently I removed that plugin.
phpstorm 9
magicento ~ installed phpstorm plugin manager
Are you opening multiple projects at the same time? No, only 1 after install plugin & phpstorm restart.

**Comment by enriquepiatti** [comment]
so that happens with the trial version right? if you have the full version you need to install it manually as described in magicento.com
