### ISSUE TITLE
Eval.php doesn't do anything when executed

### ISSUE THREAD

**Issue by AreDubya** [enriquepiatti/Magicento#174]
Hi Enrique,

I have configured Magicento to successfully connect to my server previously, with other Magento projects. 

I just set up a new project, with identical settings. Oddly, when I click 'Test PHP' in the Magicento settings, I get a 'Error: no response. Please check your configuration and test again' error. After I hit 'OK', then close the settings window, a small window pops up that says 'PHP Works!'. 

eval.php is being uploaded properly, but when I try to toggle template hints, nothing happens. I can navigate directly to var/magicento/eval.php, which shows the number 1 on the page, but again, nothing happens. 

When I do an Alt-M -> Enable Template Hints, I get this in the Event Log : 

12:31:23 PM Magicento Notification: Template hints are now Enabled

But, trying the same thing 30 seconds later, I get this : 

12:31:53 PM Magicento Notification: Template hints are now Enabled

I can confirm from the file date that eval.php is being uploaded, but Magicento is unaware of the state of the template hints, and even on direct navigation nothing happens. Can you think of anything that would cause this?

This is the content of eval.php : 

'<?php define('PATH_TO_MAGENTO', '../..');require_once PATH_TO_MAGENTO.'/app/Mage.php';Mage::app('');$websiteIds = Mage::getModel('core/website')->getCollection()->getAllIds();$storeIds = Mage::getModel('core/store')->getCollection()->getAllIds();$config = new Mage_Core_Model_Config();$pathTemplateHints = 'dev/debug/template_hints';$pathBlockHints = 'dev/debug/template_hints_blocks';$current = Mage::getStoreConfig($pathTemplateHints);$toggle = 1 - $current;$config->saveConfig($pathTemplateHints, $toggle, 'default', 0);$config->saveConfig($pathBlockHints, $toggle, 'default', 0);foreach($websiteIds as $id){$config->saveConfig($pathTemplateHints, $toggle, 'websites', $id);$config->saveConfig($pathBlockHints, $toggle, 'websites', $id);}foreach($storeIds as $id){$config->saveConfig($pathTemplateHints, $toggle, 'stores', $id);$config->saveConfig($pathBlockHints, $toggle, 'stores', $id);}$cacheTypes = Mage::app()->getCacheInstance()->getTypes();if(isset($cacheTypes['full_page'])){   $fpc = $cacheTypes['full_page'];   if($fpc->getStatus()){       Mage::app()->getCacheInstance()->flush();       Mage::app()->cleanCache();       $fpc=@class_exists('Enterprise_PageCache_Model_Cache');       if($fpc){           Enterprise_PageCache_Model_Cache::getCacheInstance()->clean(Enterprise_PageCache_Model_Processor::CACHE_TAG);           Mage::app()->getCacheInstance()->cleanType('full_page');       }   }}echo $toggle;'

Thanks for any input!

**Comment by enriquepiatti** [comment]
what do you mean with eval.php is uploaded correctly? are you using a remote server or a local Magento server?
also, could you try some other PHP features? like Eval in Magento, type something easy just like 1+1, you should receive "2" as response
if that works, then is probably something related with your Magento (maybe the cache is enabled and that is preventing the activation of the template hints or things like that)

**Comment by AreDubya** [comment]
Hi Enrique, 

Yes, it is a remote server. I originally had to do a bit of head scratching to get Magicento up with remote, but it has been working great. This issue didn't make a lot of sense to me, but your comments made me look at the file system permissions (different os than I am used to), and after a few tries I have everything working. It's not my server, and I'm not sure why this was happening, but the permissions were being reset for the var folder which was causing a bunch of issues. Thanks for the reply, everything is all good here!
