### ISSUE TITLE
Software caused connection abort

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#176]
What does this mean? And how to solve it?

```
Magicento Notification: Software caused connection abort (Please check if this URL is accessible: http://domain.de.dev/var/magicento/eval.php)
```

When I access the file with a browser, I get "1".

**Comment by SeoFood** [comment]
Same for me. Is there any debug mode?

**Comment by enriquepiatti** [comment]
@SeoFood please read in Magicento settings how the PHP features works, is explained there
Basically it create an eval.php and tries to execute that in your Magento, you can debug the eval.php just like any other php file (put a breakpoint and execute it from your browser)
What version of PhpStorm and Magicento are you using?

**Comment by Schrank** [comment]
I found the cause for me: I have a software installed called `TripMode` which makes sure, that only special programs are allowed to connect (to the internet) while I'm tethering. Unfortunately it blocks all traffic :-/
