### ISSUE TITLE
Magicento website is down

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#178]

**Comment by enriquepiatti** [comment]
Hi @ihor-sviziev where are you from? for some reason my server keeps blocking some countries, I will try to move everything to another server soon if this problem continue

**Comment by ihor-sviziev** [comment]
I'm from Ukraine

**Comment by enriquepiatti** [comment]
Hi @ihor-sviziev, I have moved the site to another server, could you test it again please? Thanks !

**Comment by ihor-sviziev** [comment]
Yes, thank you!

**Comment by pwilkowski** [comment]
Hi,
Website seems to be down again (for whole poland) and works for example for USA. Could you please fix? I was about to buy plugin.
