### ISSUE TITLE
Problem/crash while editing layout xmls

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#18]
magicento enabled, php execution disabled

When I edit a layout XML file, I get this alert window: 

> **Magicento Layout Error**
> This feature is supported only with PHP Enabled at the moment.
> Please enable PHP going to File > Settings > Magicento

after a click on "OK" there are two scenarios:
1. phpstorm freezes
2. there is a second alert window:

> **Error**
> <No Text>

And a entry in the log:
11:44:39 IllegalStateException: @NotNull method com/magicento/models/xml/MagentoXmlTag.getAllNodesFromMergedXml must not return null: @NotNull method com/magicento/models/xml/MagentoXmlTag.getAllNodesFromMergedXml must not return null

**Comment by Schrank** [comment]
if php execution is enabled and a local url given, phpstorm freezes too.

**Comment by enriquepiatti** [comment]
This should be fixed in v0.9.7.
The layout features are not ready yet, it's a temporary release for solving this issue because it was blocking the IDE.

**Comment by Schrank** [comment]
Much better, thank you!
