### ISSUE TITLE
Clear cache doesn't work with Cm_Cache_Backend_File installed

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#181]
We love to work with https://github.com/colinmollenhour/Cm_Cache_Backend_File because it is a lot faster then the default Zend_Cache_File implementation.

The problem is, the cache files look like this:
![bildschirmfoto 2015-11-19 um 09 32 38](https://cloud.githubusercontent.com/assets/379680/11265897/84f2fbb2-8ea0-11e5-82b8-ea5a9ca7577e.png)

and it seems like magicento doesn't flush them. I haven't digged into the magicento.php call, so not 100% sure.

**Comment by enriquepiatti** [comment]
Hi Fabian, the file to check is "eval.php" normally you can find that inside ./idea/magicento/eval.php or /var/magicento/eval.php if you have chosen to create that inside "var"
This is the code generated by Magicento inside eval.php when using ALT+M > Flush Cache:

`<?php
define('PATH_TO_MAGENTO', '../..');
require_once PATH_TO_MAGENTO . '/app/Mage.php';
Mage::app('');
Mage::app()->getCacheInstance()->flush();
Mage::app()->cleanCache();
$fpc = @class_exists('Enterprise_PageCache_Model_Cache');
if ($fpc) {
    Enterprise_PageCache_Model_Cache::getCacheInstance()->clean(Enterprise_PageCache_Model_Processor::CACHE_TAG);
    Mage::app()->getCacheInstance()->cleanType('full_page');
}
echo '1';`

I will improve that a bit in the next release, and I'm thinking in allowing to edit the PHP code for all php actions in Magicento from some config, so you can customize and check it easier just in case (every environment is different, so is difficult to make something 100 relieable and generic on these things)

But you have already an option in Magicento to do these type of things that are particular for your project. You can use Magicento Php Scripts:

http://magicento.com/#magicento-php-scripts

With that option your own actions to be executed by Magicento (in PHP no need to know anything about Java or PhpStorm). You can also have some input parameters. And if you think the script could be helpful for something else you can share it and other Magicento users could download, use and vote for it.
