### ISSUE TITLE
Can't rewrite block - Couldn't find class node containing Yoast_MetaRobots_Block value

### ISSUE THREAD

**Issue by AreDubya** [enriquepiatti/Magicento#183]
Hi Enrique, 

I am trying to rewrite a block, but I get this error message : "Couldn't find class node containing Yoast_MetaRobots_Block value". I haven't seen this before, not sure what it means exactly.

Thanks

**Comment by enriquepiatti** [comment]
Hi @AreDubya could you please show me the class you are trying to rewrite, and the corresponding config.xml for that module?
(if the information is private you can send it to contact@enriquepiatti.com)

**Comment by enriquepiatti** [comment]
@AreDubya I'm closing this, if you have more information or the problem stills there please reopen or send me an email
