### ISSUE TITLE
Remove installer not working for data updates?

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#19]
I have a Magento shop with data upgrade scripts and use the function "Remove this installer from core resource table".

I get the error
"Error: Installer was not reseted to previous version"

Mage.php seams to be functional as I can use "evaluate code in Magento" properly.

**Comment by enriquepiatti** [comment]
Yes I saw this error too, anyway even when the message says that, the script was working to me. Please tell me if you are seeing the same. Also you can try to use PHP with HTTP instead and see what happens.

**Comment by amenk** [comment]
Yes I checked it again. It is like you say. It is indeed updating the data_version for the setup resource properly - but the confusing message is appearing.

**Comment by enriquepiatti** [comment]
Yes I will fix it don't worry (y)

**Comment by amenk** [comment]
Works beautifully now.
