### ISSUE TITLE
\Mage is not recognized as Mage

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#194]
I'm writing tests inside of namespaces, therefore I either have to `use Mage;` or have an absolute path like `\Mage`.

When I `use Mage;` everything is fine.- But if I'm replacing every Mage with `\Mage` the recognition of the special method(s) (at least getModel) doesn't anymore work, e.g.

```
$projectImporter = \Mage::getModel('xxx/import_project');
$projectImporter->import($project); 
// >> Method 'import' not found in false|Mage_Core_Model_Abstract
```

**Comment by enriquepiatti** [comment]
Hi @Schrank is there any big issue with having the "use Mage;" then if that works? because this is a very special situation, normally we don't use namespaces with Magento1

**Comment by Schrank** [comment]
No there isn't. Everything is fine. I can work with it and I like to work with it, so there is even no egoistic/centric reason to fix this :-)

It is more "you should know" :)

**Comment by enriquepiatti** [comment]
OK, thanks @Schrank ! I will close the issue then, I prefer to keep Magicento type inference simpler, if not it could run slower, and namespaces are not needed neither common in Magento1
