### ISSUE TITLE
Magento2 - change root detection

### ISSUE THREAD

**Issue by gamort** [enriquepiatti/Magicento#196]
My project root tends to be one level up from the webroot.

Ie path on server:
$HOME/somepath/html  <--- magento installation
PHPStorm project:  somepath/html
That allows me to keep a bunch of bash scripts at
somepath/local and somepath/bin and they don't clutter up html

It looks like the plugin for version1 allows configuration of where magento is, but for magento2 there is no configuration

**Comment by enriquepiatti** [comment]
Hi @gamort Magicento2 is still in beta, I will try to make it compatible with different project structures, but I highly recommend to create a new project based on Magento root folder by now. 
Are you working normally at the same time on those bash scripts and also in Magento code? because if you can separate them then is better to have 2 PhpStorm projects, everything should run faster in that way

**Comment by enriquepiatti** [comment]
This should work fine with last Magicento2 version (1.2.0), you can config the correct path to Magento2 source in Magicento2 settings.
Please reopen if it doesn't work fine for you

**Comment by just-tom** [comment]
Hi @enriquepiatti 
I am trying to set the path to the Magento2 source but consistently receiving this error:

<img width="1395" alt="Screenshot 2019-06-27 at 11 39 32" src="https://user-images.githubusercontent.com/12802934/60260035-7c725d00-98d0-11e9-98e9-0e06689fdb95.png">

I have tried all sorts of paths, and have the latest version, so not sure where to go?

Thanks

**Comment by enriquepiatti** [comment]
Hi @just-tom can you send a screenshot showing your project folder structure? by email if it's private: contacto@enriquepiatti.com

**Comment by ricardogonort** [comment]
Hi @enriquepiatti 
 im have the same problem, the path is not valid

my path is: 
C:\Users\username\PhpstormProjects\smu

thanks

**Comment by ricardogonort** [comment]
Hi @just-tom, Could you fix the problem?
How you did it?

Thanks

**Comment by enriquepiatti** [comment]
@ricardogonort I cannot help you only with that info, please read my comment from above, I need to see your project folder structure, if that's a private info you can send it to my email
