### ISSUE TITLE
magicento 2 version on official website not correct

### ISSUE THREAD

**Issue by refaelgold** [enriquepiatti/Magicento#197]
Hey , i use magicento when i buy it from  http://magicento.com/ and the current version is  0.3.2 and on the website the latest is 2.1... how i could know when i needed to upgrade my extension?

**Comment by enriquepiatti** [comment]
Hi @refaelgold Magicento2 is still in beta, you can read always the full changelog in your plugin description inside PhpStorm. I will update the website and inform about updates on twitter account @magicentoplugin
