### ISSUE TITLE
File-based rewrite conflicts solved

### ISSUE THREAD

**Issue by halk** [enriquepiatti/Magicento#199]
Enrique,

rewrite conflicts are a pain in larger Magento projects and I like that Magicento warns about them. I'd like to share the list of resolved rewrites with the team. Wondered if there is a way I can commit it to the VCS we use.

Without we have too many warnings of rewrites we already resolved and ultimately don't react anymore to the warnings.

**Comment by enriquepiatti** [comment]
Hi @halk in next version rewrites conflict will be a bit smarter (if the rewrites classes are extending one from another, then it will assume is a rewrite solved). But until that release you can check the file inside .idea/magicento.xml in that file you will see the lis of rewrites solved, you can copy that XML node and send it to your team, they can paste it into their magicento.xml
Also take into account is really easy and fast to mark a rewrite as solved, just open the class and use ALT+M > Add to solved rewrite conflict list.
Lastly, remember you can change the config settings so Magicento doesn't check for rewrite conflicts automatically, you can always check them manually using ALT+M > check rewrite conflicts

**Comment by halk** [comment]
Thanks @enriquepiatti 

Looking forward to that
