### ISSUE TITLE
Compare Tool

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#2]
Hi!

even this is not a Magento-only function it somehow might make sense to cover this with Magicento to reflect Magento fallbacks / overwriting.

In Magento we can overwrite
- phtml files in own themes
- class files in the app/code/local

I would be nice if there is a menu entry that allows to compare a custom file with the original version.
Also it would be interesting to do this across branches ( compare my company/theme/view.phtml with the base/default/view.phtml in another branch). This is very usefull when updating and cleaning up shops.

Alexander

**Comment by enriquepiatti** [comment]
Hi Alexander, you can compare two files with PHPStorm, with different branches is a bit more difficult but you could copy the content from one branch and use compare with clipboard.
But maybe I'm not understanding your request...

**Comment by amenk** [comment]
Hi,

yes - the PHPStorm functionality should be used.

But if I want to compare my template to the base/default one this requires some navigating in the file tree.

My question is if Magicento could add some kind of context menu entry to compare a template file with the templates from other themes, especially the base/default copy. (and then of course use the standard compare of PHPStorm).

Alexander

**Comment by enriquepiatti** [comment]
OK, I think it's possible, at really I have finished a new feature for creating a copy of any template on any other package/theme.
I have added your request to the user voice list:
https://magicento.uservoice.com/forums/174928-suggestions

**Comment by amenk** [comment]
Hi,

but this is not only interesting for templates - it is also interesting for overwritten classes.

Alexander

**Comment by enriquepiatti** [comment]
This should be working in the last release (v0.8) use Alt+M (Option+M), if the current file has a corresponding "original" file you will see an option "Compare with Original".

**Comment by amenk** [comment]
This is so incredible! Thank you so much!
