### ISSUE TITLE
Some factory methods not working

### ISSUE THREAD

**Issue by tmotyl** [enriquepiatti/Magicento#20]
Some factory methods are not working - no type hints, no jump after ctrl+click:
e.g.
Mage::getResourceModel('catalog/product_attribute_collection');
Mage::getResourceSingleton('catalogsearch/fulltext_engine');

Mage::helper('catalogsearch')
Mage::helper('enterprise_giftcardaccount')

**Comment by enriquepiatti** [comment]
it works for me tmotyl, are you sure you have the last magicento version and you have the rigtht configuration on File > settings > Magicento ?
