### ISSUE TITLE
PhpStorm 2016.2(.1) - can't apply Magicento's PHP execution settings

### ISSUE THREAD

**Issue by ghost** [enriquepiatti/Magicento#201]
OS: Windows 10 x64
PhpStorm 2016.2 and 2016.2.1

After changing any Magicento settings, the button 'apply' is unclickable.
If I change settings and click 'yes' - changed value is stored, but when I return to settings again and try to test PHP execution after changing to PHP interpreter, I get "Please apply changes first".

**Comment by enriquepiatti** [comment]
Hi @DmytroRublov, I have added a bugfix for that error, please download and install Magicento again.
Thanks for reporting it!
I'm closing this, reopen if the fix doesn't work

**Comment by ghost** [comment]
Thanks a lot, @enriquepiatti, it works great now!
