### ISSUE TITLE
My user is disabled

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#203]
Hello!

I've payed about October, 18 linsence renew http://easycaptures.com/fs/uploaded/1109/1295151350.png , but today got an error

12:47    Magicento Notification: Magicento user is not valid (Wed Oct 19 00:00:00 EEST 2016)

**Comment by enriquepiatti** [comment]
Hi @Koc, please contact me by email, this information could not be so safe here in a public space. 
Send me an email with your private link (but this is a problem with the license validation, make sure you are puting the correct user code in Magicento settings and that is validated correctly, you will see your username and email below if it's correct)

**Comment by Koc** [comment]
Looks like I haven't replaced my linsence code with new after renew.

**Comment by kkrieger85** [comment]
Same for me: I bought my first license with an other email/username than I bought my second license. 

@enriquepiatti How to fix that? I cannot change Username/email in PHPStorm

**Comment by enriquepiatti** [comment]
@kkrieger85 contact me by email for problems with your license, I can't help you from here, is a public thread
