### ISSUE TITLE
version 3.0.2 keeps crashing

### ISSUE THREAD

**Issue by dbashyal** [enriquepiatti/Magicento#204]
I just upgraded Magicento to version: 3.0.2 (full version)
: to use with Magento ver. 1.14.2.4 
: on PhpStorm ver. 2016.2, Build #PS-162.1121.38, built on July 12, 2016

It keeps on crashing when it tries to autocomplete and I am unable to use it. I cleared Magicento cache, disabled "auto disable on crash" option, still, I need to keep clicking on "Enable Magicento"

Any Idea, how to fix this?

**Comment by enriquepiatti** [comment]
Hi @dbashyal please could you provide more info when exactly is crashing? 
Can you add detailed steps?
could you try with a clean Magento project (a clean copy from original code, don't use modman, n98 or any other), open only that clean project and test the autocomplete there, to know if it's a particular problem of the other project.

**Comment by dbashyal** [comment]
Hi @enriquepiatti, 

After I enable Magicento and try to autocomplete (ctrl+space) it crashes (auto disable) then I have to enable again. It never does autocomplete. I have reverted back to previous version and working fine. I would like to take benefit of new version but not sure why it doesn't work for me.

I don't have modman or n98 etc, so it's like a clean project currently :)

**Comment by dbashyal** [comment]
Also, FYI, I am using windows 7 if that helps.

**Comment by enriquepiatti** [comment]
it's weird, please send me an email @dbashyal I need more details and maybe some captures, also please try a new clean project anyway just to know if is a particular problem of the project (that we need to solve anyway in that case, but will be easier to find the problem)

**Comment by dbashyal** [comment]
Just sent you email. thx

PhpStorm: 2017.1.3
Magicento ver: 3.0.2
Windows: 10

[error-2.txt](https://github.com/enriquepiatti/Magicento/files/1002894/error-2.txt)
[error-1.txt](https://github.com/enriquepiatti/Magicento/files/1002893/error-1.txt)

**Comment by enriquepiatti** [comment]
Hi @dbashyal you are using an old version, that version is not compatible with PhpStorm 2017, please update Magicento or use an old version of PhpStorm (probably older than 2016)

**Comment by dbashyal** [comment]
thx. upgraded and fixed.
