### ISSUE TITLE
Compatibility issue with PHPStorm 2016.3

### ISSUE THREAD

**Issue by gdsdougherty** [enriquepiatti/Magicento#209]
There seem to be a few compatibility issues with PHPStorm 2016.3.  Most of the functionality does not seem to work at the moment.

**Comment by Sanuch** [comment]
HI @enriquepiatti 

Any updates?

**Comment by enriquepiatti** [comment]
Hi @Sanuch yes, what version are you using? last one is 3.1.0:
http://magicento.com/#changelog

**Comment by Sanuch** [comment]
Hi @enriquepiatti

Ok, thank you
