### ISSUE TITLE
[Magento2] There is no configuration in setting

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#210]
Hello!

I've installed plugin for Magento2 and there is no any configuration for it. Is it ok? Also `Alt+M` opens popup menu for Magento1. Can you detect Magento version using plugin and display different menu depends on it using same shourtcut?

**Comment by enriquepiatti** [comment]
Hi @Koc please read: http://magicento.com/#magicento2_installation

**Comment by Koc** [comment]
Yes, I've read it.

>  but Magicento2 will **allow you to use the same shortcut** for both Magicento1 and 2

As I understand correctly - it doesn't works for me.

**Comment by enriquepiatti** [comment]
@Koc have you changed the shortcut in PhpStorm settings as explained in that section?

**Comment by enriquepiatti** [comment]
@Koc I think there is a bug with automatic detection, I recommend to change the shortcut to something else for Magicento1 (or 2) to avoid the conflict

**Comment by enriquepiatti** [comment]
@Koc you need to remove Magicento1 shortcut, leave only Magicento2 shortcut, it should detect automatically if it's a Magento1 or Magento2 project after that.
If for some reason you are seeing the Magicento2 menu on Magento1 projects, then just use the option "Disable Magicento2" from that menu, and then when you use ALT+M again it should use Magicento1 menu

**Comment by Koc** [comment]
on, now I've got it. Thank you for explanation, it working. Not so intuitive but works.

**Comment by enriquepiatti** [comment]
Yes I know is not so intuitive, but that's why I wrote the instructions to install Magicento2
Glad to hear is working fine now
