### ISSUE TITLE
[Magento2] Add some actions

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#212]
* toggle template hints
* flush cache
* create theme
* copy template/layout to theme

**Comment by Koc** [comment]
@enriquepiatti please add copy template/layout to the custom theme. This is very needed action for theme integration

**Comment by Koc** [comment]
@enriquepiatti I've tryed copy template and it doesn't work: see screenshot https://yadi.sk/i/SJPJmpOa35qrbi

**Comment by enriquepiatti** [comment]
Hi @Koc can you show me your project structure? (maybe by email if it's private). It seems Magicento didn't find any Theme (it should find at least the blank and admin theme even if you don't have a custom theme in app/design)

**Comment by Koc** [comment]
It is simple theme located in app/design/frontend - https://yadi.sk/i/--m-0Bj835r2Gr . With composer.json, theme.xml and etc. Also this project is remote by sftp.

**Comment by enriquepiatti** [comment]
@Koc seems to be correct, can you try reindexing the project? File > Invalidate Cache/Restart

**Comment by Koc** [comment]
@enriquepiatti wow, it really works! Thank you.

As improvement - it is better remember last selected theme and preselect it on next action.
Also I think it is possible trigger reindex automatically on plugin updates to prevent any other problems.

**Comment by enriquepiatti** [comment]
@Koc thanks for the suggestions I will implement that (there is a Magicento2 action inside ALT+M to reindex all Magicento2 indexes only, but I have detected is not refreshing the indexes for Themes, I will fix that too)

**Comment by Koc** [comment]
see https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/ca9e0411cf38014def74829ec3bc36e1bca0ec31 for similar approach for saving last selected format and make it selected by default (useful for saving last selected theme for copy/override layout/template)

**Comment by enriquepiatti** [comment]
yes, it's done is not a difficult implementation, will be available with next release don't worry
