### ISSUE TITLE
Group new -> file actions and disable groups when plugin is not active in project

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#213]
See screenshot. It is better create some groups like Magicanto and Magicento2 and put templates under it. And disable groups for non-magento projects.

![2016-12-07_13-26-45](https://cloud.githubusercontent.com/assets/191082/20966008/0a1a4714-bc81-11e6-882c-5a68edb75e77.png)

**Comment by enriquepiatti** [comment]
I have removed those files from the menu, but you can edit the templates from PhpStorm settings

**Comment by Koc** [comment]
oh, no, it was useful. Can you just move it to subgroup like MaGinto or PHPUnit?

**Comment by enriquepiatti** [comment]
Why it was useful? It was not the idea to be used in that way, is used internally by other Magicento actions
It could confuse other users
(anyway you can just create your custom template files too and will appear on the list)

**Comment by Koc** [comment]
ok, understand, thank you
