### ISSUE TITLE
[Magento2] Provide option to clear layout cache after changes in layout xml

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#215]
Please add option to exec `php bin/magento cache:clean layout` if layout files changes

**Comment by enriquepiatti** [comment]
I think this is not needed as a special action.
Right now you can sexecute Magento2 commands with Magicento2, I have added (v1.2.0) some modifications to that dialog to make it more friendly and faster (now you can start typing the command, any part of it, even if you don't remember the command name but the word is included in the command description text) and Magicento2 will autocomplete the command for you. In this case these should be the steps to clean the cache:

1) ALT+M > Execute Magento2 Command (is the last item, but you can also start typing when the menu is shown and options will be filtered)
2) Start typing the command, any part, for example: "clean"
3) (option) hit TAB and type layout (if you want to clean only layout)
4) hit ENTER
