### ISSUE TITLE
[Magento2] Autocomplete and resolve types for object manager

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#218]
```php
$scopePool = ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopePool'); // no autocomplete of class name here.
$scopePool-> // no autocomplete here
```

**Comment by enriquepiatti** [comment]
Last version (1.2.0) recognizes some Object Manager calls (it needs the explicit string for the class name), but just because Magento2 is using it in their code, remember you need to try to avoid ObjectManager calls directly

**Comment by Koc** [comment]
@enriquepiatti autocomplete for methods works ok, but autocompletes for class names that pass to `get` method not works.

**Comment by enriquepiatti** [comment]
that's because is not a recommended action @Koc you should not use the Object manager directtly, why you need that instead of using DI? if there is a good use of that I will implement it, if not I think is like promoting a bad practice
