### ISSUE TITLE
[Magento2] Resolve getResource/getResourceCollection/getCollection inside models

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#220]
```php
namespace Magento\Catalog\Model;
class Category extends \Magento\Catalog\Model\AbstractModel implements
    public function getDefaultAttributeSetId()
    {
        return $this->getResource()->getEntityType()->getDefaultAttributeSetId();
    }
}
```
Method `getEntityType` determinated as undefined. But Magicento can detect that `getResource` method will return instance of `Magento\Catalog\Model\ResourceModel\Category` and override vdoc for getting autocomplete and ctrl+click work properly.

Similar for methods like `getCollection`, `getResourceCollection`.

**Comment by Koc** [comment]
![2017-05-01_19-15-28](https://cloud.githubusercontent.com/assets/191082/25585338/ab4451a0-2ea2-11e7-8560-a8c097118d8e.png)

Also would be nice resolve collection iterators

**Comment by Koc** [comment]
Also noticed that `create new crud model` generates invalid phpdocs

```php
<?php

namespace Brouzie\Satin\Model;

/**
 * @method ${
RESOURCENAME
} getResource()
 * @method ${
RESOURCENAME
}\Collection getCollection()
 */
class Warehouse extends \Magento\Framework\Model\AbstractModel implements \Brouzie\Satin\Api\Data\WarehouseInterface,
    \Magento\Framework\DataObject\IdentityInterface
{
    const CACHE_TAG = 'brouzie_satin_warehouse';
    protected $_cacheTag = 'brouzie_satin_warehouse';
    protected $_eventPrefix = 'brouzie_satin_warehouse';
}
```

something wrong with placeholders `${RESOURCENAME} `

**Comment by Koc** [comment]
looks like types resource models and collections are resolved properly, thank you very much. Still remains to implement:

- `getItems`
- iterator (when iterating collection using foreach without calling `getItems`)

**Comment by Koc** [comment]
also when I call any method which returns `$this` (for example `load`) - plugin looses resolved types

```php
foreach ($collection as $item) {
    $item-><autocomplete ok>
}

foreach ($collection->load() as $item) {
    $item-><no autocomplete>
}

```

**Comment by enriquepiatti** [comment]
@Koc why you are using a for like that? load is not needed, is automatically called if needed when you are looping the collection

**Comment by Koc** [comment]
`load` just for example

**Comment by enriquepiatti** [comment]
can you show real examples where you need that? (is a bit difficult to detect the return this on PHpStorm due the way they manage the index)

**Comment by enriquepiatti** [comment]
It's too difficult to detect all return $this, is better just to $collection->load(); before the foreach, and use only $collection inside the foreach
