### ISSUE TITLE
Magicento wrongly rewrites class Mage_Tax_Model_Sales_Total_*

### ISSUE THREAD

**Issue by pinglu** [enriquepiatti/Magicento#223]
For all classes within Mage_Tax_Model_Sales_Total_* the correct config.xml rewrite would be:

`
<models>
            <Foo_Tax>
                <class>Foo_Tax_Model</class>
            </Foo_Tax>
            <tax>
                <rewrite>               <sales_quote_totals_tax_shipping>Foo_Tax_Model_Sales_Total_Quote_Shipping</sales_quote_totals_tax_shipping>
...
`

When in the class using Magicento, it will create the following rewrite:
`<sales_total_quote_shipping>Foo_Tax_Model_Sales_Total_Quote_Shipping</sales_total_quote_shipping>`

which somehow partially rewrites the class as it will jump in the rewrite but not all the time. Haven't debugged it further. But with the first, and correct rewrite it will truly rewrite the class.

**Comment by enriquepiatti** [comment]
Hi @pinglu could you explain this better? the class rewrite system is the same for any class, Magicento seems to be doing it correctly, if sometimes works and sometimes not then must be something else in your code
