### ISSUE TITLE
[Magento2] Add autocomplete for helper classes and helper methods

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#224]
```php
<?php /* @var $block \Magento\Catalog\Block\Product\View\Description */ ?>

<?php $_helper = $this->helper('<add autocomplete here, please>'); ?>
<?php $_helper-> <add autocomplete here, please> ?>
```

**Comment by enriquepiatti** [comment]
I've added the type recognition (v1.2.0) for helpers and object managers, but not sure if we need or is even a good idea to add autocomplete for those strings, the idea is to avoid using the object manager directly in Magento2 (even when they are using in their code, but they are trying to move all those lines to DI too)

**Comment by Koc** [comment]
helper methods autocompletes ok, but helper classes not autocompletes (like in #218)

**Comment by enriquepiatti** [comment]
same comment in #218 :)

**Comment by Koc** [comment]
it used in some original magento phtml templates and useful for some simple changes in theme templates

**Comment by enriquepiatti** [comment]
yes, it is used by Magento original files (and the team from Magento are saying this is a bad practice, they will change this in the future probably). But that's why I think is ok to have the type recognition (because there is code already using Object Manager directly) but is not needed the autocomplete because we should not write new code in that way.

**Comment by enriquepiatti** [comment]
Some discussions about this:

http://magento.stackexchange.com/questions/74526/magento-2-accessing-a-helper-without-using-constructor-injection

http://magento.stackexchange.com/questions/10517/instantiating-helpers-in-magento-2

http://magento.stackexchange.com/questions/140409/magento-2-when-to-use-object-manager-in-unit-tests/140455
