### ISSUE TITLE
Error on setup:static-content:deploy from Execute Magento Command window

### ISSUE THREAD

**Issue by AreDubya** [enriquepiatti/Magicento#227]
Hi Enrique, 

I was trying to run setup:static-content:deploy on a specific theme, and kept getting this error 

Error: [InvalidArgumentException] "Rw/grad" argument has invalid value, available themes are: Magento/blank, Magento/luma, Magento/backend, Sm/market, Rw/grad setup:static-content:deploy [-d|--dry-run] [--no-javascript] [--no-css] [--no-less] [--no-images] [--no-fonts] [--no-html] [--no-misc] [--no-html-minify] [-t|--theme[="..."]] [--exclude-theme[="..."]] [-l|--language[="..."]] [--exclude-language[="..."]] [-a|--area[="..."]] [--exclude-area[="..."]] [-j|--jobs[="..."]] [--symlink-locale] [languages1] ... [languagesN] Executing :/usr/bin/php7.0 [-dxdebug.remote_enable=0, /var/www/html/gradys/bin/magento, setup:static-content:deploy, --theme="Rw/grad"] with Interpreter Remote PHP 7

It took me a minute to notice it, but quotes are getting  inserted around the theme name, which shouldn't be there. With them removed the same command works without error from bash.

**Comment by enriquepiatti** [comment]
@AreDubya this error happens only when using PHP Interpreter for the commands, but will be fixed in next version. Thanks !
