### ISSUE TITLE
[Enhancement] Add module name to class name suggestions for rewrites

### ISSUE THREAD

**Issue by Vinai** [enriquepiatti/Magicento#24]
When using the (very neat) class rewrite tool in Magicento, the suggested class name simply copies the class inside the object type directory to the new module. For example
`Mage_Catalog_Model_Product` is rewritten to `Foo_Bar_Model_Product`.

This is problematic if classes with the same class name inside the module are rewritten inside a single module, for example `Mage_Sales_Helper_Data` and `Mage_Customer_Helper_Data`. Even more so if the target module needs to have it's own data helper, too.

Following best practice all rewrites should be in a folder structure as follows (with a matching class name of course):

[namespace] / [modulename] / [objecttype] / [orig-modulename] / [class]

For example:

`Mage_Catalog_Model_Product`rewrite to `Foo_Bar_Model_Catalog_Product`  
`Mage_Catalog_Helper_Data` rewrite to `Foo_Bar_Helper_Catalog_Data`  
`Mage_Sales_Model_Resource_Quote` rewrite to `Foo_Bar_Model_Sales_Resource_Quote`  

Of course this doesn't handle all cases, it would be quite a lot cleaner. The few cases where the namespace name is needed in order to achieve a unique name are extremely rare (like when rewriting `Foo_Catalog_Helper_Data` and `Mage_Catalog_Helper_Data`).  
Always including the namespace in the target class name would be even cleaner, but arguably the resulting class names might be a little unpractical.

**Comment by enriquepiatti** [comment]
Done in v1.3.0

**Comment by Vinai** [comment]
Thank you!
