### ISSUE TITLE
PhpStorm 2017.14 - Magicento 2.0 unable to run test PHP

### ISSUE THREAD

**Issue by ppadmapati** [enriquepiatti/Magicento#243]
Hi,

I installed the magicento 2.0 plugin yesterday and was trying to run "Test PHP". Nothing happens when I click "Apply Changes" and I get the message "Please Apply Changes first" when I click on "Test PHP". Tried different variations but getting the same outcome.

Regards,
Pranjal

**Comment by enriquepiatti** [comment]
Hi @ppadmapati what version of Magicento2 and PhpStorm are you using? please send me an email, I will need some screenshots

**Comment by ppadmapati** [comment]
Hi @enriquepiatti,

Thanks for your prompt response. I am very new to the platform and, hence,
you will have to guide me to the screenshots you need. However, I am
sending you the screenshot I think will be useful to you.

PhpStorm Version - 2017.1.4
Magicento Version 2. I don't know if there is a more specific version
number. Providing my order number in case it helps you -
*8UW1332201183852C*

Sending you the screen shot where php test does not run

[image: Inline image 1]

Regards,
Pranjal

**Comment by enriquepiatti** [comment]
@ppadmapati I had to remove your post, this is a public thread, don't post your private info here please, send me an email

**Comment by enriquepiatti** [comment]
fixed in 1.6+
workaround (for v1.5 or before): select your editable modules from Magicento2 settings, don't leave it empty
