### ISSUE TITLE
[Magento1] Error creating Adminhtml Controller with custom admin route

### ISSUE THREAD

**Issue by ghost** [enriquepiatti/Magicento#251]
Can't create a adminhtml controller if I have a custom route for my store admin in local.xml. See image attached.

My etc/local.xml configuration of custom admin url, generated by Magento Installer:
` <admin>
        <routers>
            <adminhtml>
                <args>
                    <frontName><![CDATA[backoffice]]></frontName>
                </args>
            </adminhtml>
        </routers>
    </admin>`

If I remove this configuration in local.xml, the new controller dialog works.

![image](https://user-images.githubusercontent.com/1138923/27928136-68ff07cc-6264-11e7-81e3-42d16bef1951.png)

Thank you.

**Comment by enriquepiatti** [comment]
Hi @mmswebinternet thanks for reporting, please download and install Magicento again v3.1.2 should have this bug fixed
