### ISSUE TITLE
[Magento2] Allow create controller when route already exists

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#252]
Currently when I create new controller, plugin asks me for route id and front name. And when I create second or third controller - it asks this params again. Also it append them to `routes.xml`.  As I understand correctly - it requires only for first controller in module. It is needed remove generated stuff from `routes.xml` each time on new controller creation.

**Comment by enriquepiatti** [comment]
Thanks @Koc I have added support for existent routes, will be available with v1.6 soon
