### ISSUE TITLE
[Magento2] Exclude tests from project

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#253]
Almost each Magento 2 module comes with tests. All of them are indexed. Also goto class/file or search goes through them. Usually I'm just adding them to ignored forlders. But in typical Mage2 project we need mark it as excluded for each composer module.

IMHO this plugin can do it programatically depends on config option.

**Comment by Koc** [comment]
ref https://github.com/Haehnchen/idea-php-phpunit-plugin/issues/20

**Comment by enriquepiatti** [comment]
With v1.7.0 there is a new config in Magicento2 to add all the test folders to the Ignored list, please check if this works ok for you
