### ISSUE TITLE
Typing letter "m" suggests "massdeleteaction"

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#255]
Looks like this is code generation from Magicento1, but this project using Magicento2

![default](https://user-images.githubusercontent.com/191082/28249342-9dcf5bd2-6a5c-11e7-8201-3994f797980a.png)

![default](https://user-images.githubusercontent.com/191082/28249345-afb745a8-6a5c-11e7-92de-986d14de85ef.png)

**Comment by Koc** [comment]
Looks like you have selected too much items in live templates

![default](https://user-images.githubusercontent.com/191082/28360673-d1fb80a6-6c7e-11e7-8813-681aea4f3bb0.png)

**Comment by enriquepiatti** [comment]
Thanks @Koc, you can download v3.1.4 (use your private link) to fix that (now only "Statement" option should be selected for Live Templates from Magicento) or just unselected them directly from those settings (maybe even easier than reinstalling Magicento)

**Comment by Koc** [comment]
good
