### ISSUE TITLE
PHPStorm crashes sometimes on project exporing or navigation to file

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#259]
This issue occurs time to time. I've recorded the video - crash with enabled plugins and no crash when both plugins are disabled.

http://youtu.be/tV0U3KJDYn8?hd=1
Also I've attached phpstorm error log.

[java_error_in_phpstorm_10472.log.txt](https://github.com/enriquepiatti/Magicento/files/1181036/java_error_in_phpstorm_10472.log.txt)

**Comment by Koc** [comment]
external issue https://youtrack.jetbrains.com/issue/WI-34324 (closed by PHPStorm team)

**Comment by enriquepiatti** [comment]
@Koc is the conflict with Magicento1 or Magicento2?
Also, can you detect another error, with a better stack trace before the IDE crashes?

**Comment by Koc** [comment]
What another error? How can I get this better stack trace?

**Comment by Koc** [comment]
aah, I understand. Another error is https://github.com/enriquepiatti/Magicento/issues/257

**Comment by enriquepiatti** [comment]
OK, is with Magicento1 or Magicento2? please disable only one not both at the same time to test that
And after that also try disabling the plugin from Magicento settings (not from Plugins settings) to see if that solves the problem too or even when is disabled from the settings is crashing the IDE

**Comment by Koc** [comment]
No more occurs on fresh Windows 10 installation. 🙏
