### ISSUE TITLE
Couldn't find class node containing Mage_Core_Model value

### ISSUE THREAD

**Issue by fplantinet** [enriquepiatti/Magicento#26]
When i try to rewrite class : Mage_Core_Model_Store
i have this error : 
Couldn't find class node containing Mage_Core_Model value

![magi](https://f.cloud.github.com/assets/2428023/25429/2a9818aa-4ae2-11e2-8920-e3f7b9b6cbab.PNG)

**Comment by enriquepiatti** [comment]
Done in v1.3.0
