### ISSUE TITLE
Typing results in backwards words Magicento 2

### ISSUE THREAD

**Issue by headlinedev** [enriquepiatti/Magicento#260]
1. Open Magicento 2
2. Create Controller
3. Type Category results in yrogetaC in all fields

**Comment by enriquepiatti** [comment]
Hi @HeadlineInteractive what Magicento and PhpStorm and OS are you using?
I cannot reproduce this bug, I have asked to Jetbrains team too and they don't have any clue about what could be causing this (the UI components are created by them, not Magicento).
But some other user told me about this too in the past, I think he solved it reinstalling PhpStorm and Magicento, or maybe was some other conflict not sure. Can you check if Magicento is showing some other error (check the lower right corner in PhpStorm, the error stack trace is there)

**Comment by headlinedev** [comment]
Hi @enriquepiatti after rebooting my system it is working again. Thanks for the reply
