### ISSUE TITLE
Add private office/restore download link on magicento site

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#262]
Hello!

New version of Magicento and Magicento2 is out, but I haven't option download new version on `alt+m`. I need download link, but it somewhere in my big inbox. Please add possibility restore download link to your products (just enter email and got download links for all products).

Or add private office where I can get info about my products and their expiration date.

**Comment by Koc** [comment]
Also you can send newsletters with download link if new version is out.

**Comment by enriquepiatti** [comment]
Download option could take some time to appear, but inside your Magicento settings you have your user code, you can download Magicento just using that: 
http://www.magicento.com/rest/plugin/download?key=[YOUR CODE HERE}
I will add that inside the settings too just in case
