### ISSUE TITLE
[magento 1] jump to observer method from config.xml does not work

### ISSUE THREAD

**Issue by oleggusev** [enriquepiatti/Magicento#268]
Please, see my video:
http://take.ms/u9sJ9i

I refreshed magicento indexer, but still does not work (for much things) in last version very much things do not work, could I downgrade my module?

Thank you very much.

**Comment by enriquepiatti** [comment]
are you sure Magicento is enabled @oleggusev ? it should work fine, those features were not changed and it was tested multiple times with PS2017.2.
Anyway, if you need an old version for some reason you can download using your private link and appending &v=old

**Comment by oleggusev** [comment]
Yes, I'm sure it is enabled, I even switched on/off it several times AND Alt-M work perfect, refresh cache and os on. Such problems comes with last versions, prev it works fine.
It works when no need to detect class, please, see:
http://take.ms/TOPXP <http://take.ms/TOPXP>

it is the same project!

Thank you very much.
------------------------------------------------
Best regards,
Oleg Gusev,

Magento Certified Developer Plus Programmer & Consultant/Team Lead/Founder
Dnipro Magento Developer Team, CreateStores Inc.
Ukraine
Skype: praetorianv
Email: magentoassistance@gmail.com <mailto:magentoassistance@gmail.com>
IN: https://www.linkedin.com/in/createstores <https://www.linkedin.com/in/createstores>

**Comment by enriquepiatti** [comment]
@oleggusev can you check if there is some error on the IDE? (bottom right corner, you should see a red icon and error details there).
Also, can you test if the "factory string" works in PHP code (not XML), use CTRL+B (or CTRL+click or middle click, or any goto shortcut you are using) somewhere like Mage::getModel('HERE')

**Comment by oleggusev** [comment]
No, sorry, there are no any error in log:
http://take.ms/lRguZ <http://take.ms/lRguZ>

I can make meeting with you and share screen, or launch debug script.

Thank you very much.

**Comment by enriquepiatti** [comment]
yes, that could work, but please could you try using the GoTo feature inside the PHP code (not XML) to see if it works there?

**Comment by oleggusev** [comment]
Yes, sure, it works, if class defined:
http://take.ms/8nrB2 <http://take.ms/8nrB2>

But sometimes not... Right now I did not find the example, but when I will see such example time, I will notify you.

Thank you.

**Comment by enriquepiatti** [comment]
Hi Oleg, no I don't mean there, I mean using the GOTO with some factory string, but in PHP
Mage::getModel('USE GOTO HERE')
Mage::helper('USE GOTO HERE')
is that working?
(try using the same factory string that is not working in XML, but in PHP)

**Comment by oleggusev** [comment]
Hello, sorry for delay.

As you can see from my screen video: http://take.ms/JXtTY 
I have a problem related only to custom module, which I attached
[Shiptheory.zip](https://github.com/enriquepiatti/Magicento/files/1438278/Shiptheory.zip)
 to this ticket. But core module works.

Thank you very much.

**Comment by enriquepiatti** [comment]
Maybe is a cache problem, try refreshing Magicento cache (ALT+M) and also invalidating full PhpStorm Cache: File > Invalidate Cache / Restart
Also make sure your module does not have any errors, including upper/lowercase differences, file paths, etc, and also the module must be enabled

**Comment by oleggusev** [comment]
Hello,

Exactly: it is NOT a cache, sure I tried reinstall it and reset magicento cache and reindex... nope

Thanks.

**Comment by oleggusev** [comment]
It could be closed, after upgrade I do not see the issue. thanks.
