### ISSUE TITLE
Remove whitespace in generated config.xml for rewrite

### ISSUE THREAD

**Issue by aligentjim** [enriquepiatti/Magicento#29]
When generating a rewrite, Magicento generates

```
<rewrite>
    <some_class>
        Namespace_Extension_Model_Some_Class
    </some_class>
</rewrite>
```

When it should generate:

```
<rewrite>
    <some_class>Namespace_Extension_Model_Some_Class</some_class>
</rewrite>
```

The extra whitespace around the class name causes the factoryMethod (e.g. Mage::getSingleton to thrown an exception.

**Comment by enriquepiatti** [comment]
I can't reproduce this, I think this is related with the Wrap Text from PHPStorm.
Make sure you have this option unchecked:
Settings > Code Style > Xml > Other > Wrap text
Magicento will show you a warning about this if you try to use the autocomplete feature on any config.xml.

**Comment by aligentjim** [comment]
Thanks for your help.  Changing the Wrap Text parameter fixed the issue.  I haven't used the autocomplete functionality in config.xml at all when I logged this issue, so it might be worth adding the same setting to the rewrite as well.
