### ISSUE TITLE
[Magicento2] File templates are missing from context menu

### ISSUE THREAD

**Issue by k4emic** [enriquepiatti/Magicento#290]
In previous versions of Magicento2, you would get a list of file templates (di.xml, module.xml, webapi.xml, etc.) when right-clicking a file or folder in the project pane and expanding the "new" tab.

The templates are still listed under the "Edit file templates" menu, but does not appear in the right-click context menu. https://screencast.com/t/WJ1joRDoki

**Comment by enriquepiatti** [comment]
Those templates are used internally by Magicento2, you can edit them if you want to add something, but is not the intention to create them manually.
But If you want to create those files manually you can always create the same template on "Files" tab
