### ISSUE TITLE
[Magento 2] Multiple Content Roots in PhpStorm Project

### ISSUE THREAD

**Issue by alanablett** [enriquepiatti/Magicento#293]
Not an issue so much as an observation.

I noticed that when I had multiple Content Roots/Directories added to a project that Magicento's features would not work. It might be worth adding a note about this to the installation instructions to help others that may come up against this issue.

**Comment by enriquepiatti** [comment]
Hi @alanablett what do you mean with Magicento's features are not working? do you see some error?
Also, how do you know the content roots is the problem? if you remove them then everything works again? maybe is one particular directory the problem?

**Comment by alanablett** [comment]
Hi @enriquepiatti 

There were no errors, but the auto completion etc were not working at all. Unfortunately I've not been able to replicate the issue. Once I had removed the second Content Root everything started to work as usual. Adding the Content Root back in didnt cause the issue. Previously I had also made sure to invalidate caches etc. I'll close this but will re-open if I do manage to replicate. Thanks.
