### ISSUE TITLE
[Magicento 2][PS 2019.2] Settings not visible

### ISSUE THREAD

**Issue by kpitn** [enriquepiatti/Magicento#303]
Hi,

With the last version of phpstorm settings are not visible

![magicento](https://user-images.githubusercontent.com/41059/61955388-338af280-afbb-11e9-9442-a89e0eaa2c29.png)

![magicento2](https://user-images.githubusercontent.com/41059/61955498-70ef8000-afbb-11e9-9300-b8e3f65d5083.png)

Can you do something ?

**Comment by enriquepiatti** [comment]
Hi @kpitn please try restarting PhpStorm, and also try resizing the settings window (make it bigger)

**Comment by kpitn** [comment]
You are right, I have restart phpstorm before write the issue, but i can see the window now.

Thank You
