### ISSUE TITLE
Create module functionality

### ISSUE THREAD

**Issue by tgamanov** [enriquepiatti/Magicento#304]
PHPStorm version 2019.1.3
Magicento v3.1.5
Execution of 'create module' creates
etc/config.xml,
Helper/Data.php
Modules/Vendor_ModuleName.xml
Files registration.php, module.xml and *.json are absent.
Please let me know if you need more details.
Thanks

**Comment by enriquepiatti** [comment]
Hi @tgamanov please check if there is some error (lower right corner in PhpStorm there is an icon there which shows the errors, click also the "details" tab)

**Comment by tgamanov** [comment]
There were no errors. 
Looks like it is because both versions were installed. Even if I disable for 1st one at the settings alt+m enabling it instead of for 2nd version. 
Uninstalled magicento for 1st mage and everything is good now. 
Thank you.
