### ISSUE TITLE
[Magicento2 -1.7.1][PhpStorm 2019.2] Error when installing plugin

### ISSUE THREAD

**Issue by LukSky24** [enriquepiatti/Magicento#305]
Hey,
I have a problem installing Magicento2 in my Phpstorm. Every time I want to install it (screen with the version and plugins is attached), I must restart Phpstorm, and i get a error that is shown on the screen below. Can you help me with this problem?
![error_log](https://user-images.githubusercontent.com/52952445/62295670-e224ac80-b46d-11e9-9d4c-add946042744.png)
![install_screen](https://user-images.githubusercontent.com/52952445/62295673-e3ee7000-b46d-11e9-8e8f-456748f03ae3.png)

**Comment by enriquepiatti** [comment]
What PhpStorm version are you using?

**Comment by enriquepiatti** [comment]
Can you try File > Invalidate cache restart and try again?   
Anyway, I think is a problem with 2019.2 version, could be related to this:   
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004371099-Scene-Builder-does-not-work-anymore-after-update-to-2019-2-version   
But nobody is answering about that problem.   
If you have the chance to downgrade to previous PhpStorm version I recommend that until I can find the fix

**Comment by LukSky24** [comment]
I downgraded it but it doesn't help. At the end, it was very trivial problem. I just don't have permission to write for this extension files. After I got this, this extension start working.

**Comment by enriquepiatti** [comment]
perfect, thanks for the tip, could be useful for other users
