### ISSUE TITLE
Model not fetched from Collection

### ISSUE THREAD

**Issue by hwebb** [enriquepiatti/Magicento#308]
Magicento doesn't seem to be able to fetch the Model from a Collection, which was working well in the past, as you can see on this screenshot

![image](https://user-images.githubusercontent.com/1782396/69838489-b9cb8400-128e-11ea-82b2-4696dccf3967.png)

This forces me to add a ref, which is time consuming
![image](https://user-images.githubusercontent.com/1782396/69838594-25155600-128f-11ea-8a6f-c482b410e7df.png)

I have the PHPStorm 2019.3, but it wasn't working since I changed computer a few month ago.
I'm working on Magento 1.14.X.
Magicento is enabled.

Thanks for helping me out.

**Comment by enriquepiatti** [comment]
Thanks @hwebb, can you update Magicento? this should be fixed in v3.1.7
