### ISSUE TITLE
catalog_product_save_before event is missing

### ISSUE THREAD

**Issue by tim-bezhashvyly** [enriquepiatti/Magicento#31]
When adding an observer declaration in config.xml catalog_product_save_before event is missing at the auto-completion list.

**Comment by vishalmote** [comment]
catalog_product_save_before and catalog_product_save_after is also missing in magento v-1.7.0.2 .

**Comment by enriquepiatti** [comment]
This and more events were added to the autocomplete list in v2.3.0
