### ISSUE TITLE
3 months after I purchased my license its saying its expired

### ISSUE THREAD

**Issue by compass2k** [enriquepiatti/Magicento#318]
"magicento2 user is not valid" is reporting in phpstorm popup despite I just bought it at the end of December last year.

???

**Comment by compass2k** [comment]
Still waiting a week later ...

**Comment by compass2k** [comment]
Still being ignored - took my money and lost interest eh Enrique?

**Comment by enriquepiatti** [comment]
@compass2k I saw this here today, you have my email in magicento.com for a fast answer, I don't check this here too often, only when getting notified by email that for some reason was not the case, maybe lost in the middle of thousands of other notifications :/
User is not valid is usually due some missconfiguration and is really easy to solve.
Anyway, I can see from comments in another issue you are not happy with Magicento and you think is not useful for your work so don't worry, even when I offer 30 days to request a refund in those situations and you decided to wait almost 3 months I can send you a refund, just send me an email.

**Comment by compass2k** [comment]
Yes thank you I would prefer this. Its just easier to adjust my coding to
the official plugin as I know it will be supported.

My email is ***@***.***

d

**Comment by enriquepiatti** [comment]
It seems emails are not allowed in comments, please send me an email, my address is in magicento.com
