### ISSUE TITLE
Add translate issue

### ISSUE THREAD

**Issue by dancetrain** [enriquepiatti/Magicento#32]
If translated text contains ' symbol and quoted in the same symbol like in this string
$this->__('Click &lt;a href="%s" onclick="this.target=\'_blank\'">here to print&lt;/a> a copy of your order confirmation.', ...)
Translate line will be converted to:
"Click &lt;a href=""%s"" onclick=""this.target=\'_blank\'"">here to print&lt;/a> a copy of your order confirmation."
Instead of:
"Click &lt;a href=""%s"" onclick=""this.target='_blank'"">here to print&lt;/a> a copy of your order confirmation."

**Comment by enriquepiatti** [comment]
Fixed in v1.6.0
