### ISSUE TITLE
[Jetbrains Gateway] Plugin 'Magicento' requires plugin 'com.jetbrains.php' to be installed

### ISSUE THREAD

**Issue by pquerner** [enriquepiatti/Magicento#320]
Trying out Jetbrains new tool called "Gateway" and I wanted to try out Magicento.
However I am greeting with this error message:

`Plugin 'Magicento' requires plugin 'com.jetbrains.php' to be installed`

Can this be fixed?

**Comment by enriquepiatti** [comment]
Are you using PhpStorm? if not you need to install PHP plugin of course

**Comment by pquerner** [comment]
PHP Plugin is not available in Gateway as the "client" (PHPStorm) "runs" on the other side.

https://www.jetbrains.com/remote-development/gateway/

So I cannot "install" a PHP Plugin (locally).

**Comment by enriquepiatti** [comment]
I'm not sure how it works, is a new product, sadly I cannot add support for it, maybe you can install PhpStorm in your local?

**Comment by pquerner** [comment]
I'm not using it atm, but as I thought phpstorm is running "in the backend" (where it seems I have no tell on which plugin should run) and gateway "in the frontend". Gateway just behaves as any other Jetbrains product, but will talk to the files which are not sitting locally.

Anyway, since I am not currently using Gateway I dont need support for it. I just wanted to let you know this exists, and for all I knew it was a simple way to recompile magicento against it and it wouldnt be too much trouble. It seems not, and thats fine.

Thanks for listening, take care :)
