### ISSUE TITLE
Is this plugin still being maintained?

### ISSUE THREAD

**Issue by lfolco** [enriquepiatti/Magicento#321]
I just purchased an upgrade but it's not working correctly (it keeps getting disabled in PhpStorm). I notice this repo hasn't had any activity for quite some time. Where do we go for support?

**Comment by pquerner** [comment]
This repo doesnt get updated. The plugin is closed source (for now, not sure it that ever changes).

To help with your problem, the maintainer problably needs more information about what went wrong (ie. a stacktrace) or something.

PS: I am not the maintainer.

**Comment by lfolco** [comment]
I heard back, contacted him directly.
