### ISSUE TITLE
extend recommendations at the end of the list

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#34]
When I write a new Helper

```
class Helper extends <Cmd + Space>
```

I found at the end of the list, after Mage_Adminhtml_..., Zend_Db_..., Zend_Log_... the magicento recommendation Mage_Core_Helper_Abstract

This should be at the beginning :) sometimes it is. I think with controllers. Often it is not.

**Comment by enriquepiatti** [comment]
Fixed in v1.4.1
