### ISSUE TITLE
NullPointerException when trying to use Template Path Hints

### ISSUE THREAD

**Issue by Fplus** [enriquepiatti/Magicento#36]
Hello, I'm using PHP Storm 6 and just installed the Magicento plugin. I have toggled and enabled the PHP Exception box in settings. Each time I try to turn on the Template Path Hints through Magicento, my event log returns the following error.

NullPointerException: Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.EdtRunnable$1@150c5ee,notifier=null,catchExceptions=false,when=1363969312217] on sun.awt.windows.WToolkit@d2d8c7

No path hints appear. Should I be trying to activate this only in certain file types or something? Any help would be appreciated.

**Comment by enriquepiatti** [comment]
Is this happening in all your projects? are you using a Virtual Machine? please try with different configurations for the PHP execution (for example try with the HTTP option), and try to execute some PHP code using Alt+M > Evaluate in Magento to see what happens

**Comment by enriquepiatti** [comment]
I couldn't reproduce this, please open again if the bug persists
