### ISSUE TITLE
meta definitions without meta file

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#39]
Currently the factory resolution is done using the meta file - are there plans to do this via the extension points and to also detect, when classes are changed and update information automatically?

**Comment by enriquepiatti** [comment]
yes there are plans for that, but there isn't any extension point yet :(

**Comment by amenk** [comment]
Sure? How did the Symfony2 plugin do that?

Alexey Gopachenko
08 Apr 2013 04:04
3 days ago

#
A proper plugin for Symfony2 DI calls - handling it via new EP programmaticaly
http://blog.jetbrains.com/webide/2013/04/phpstorm-6-0-1-eap-build-129-177/#comment-42470

**Comment by enriquepiatti** [comment]
Thanks Alexander! I didn't know about the new extension points, I will implement that soon.

**Comment by enriquepiatti** [comment]
Done in v1.6.0
