### ISSUE TITLE
Autocomplete class name not working after update to 1.4.1

### ISSUE THREAD

**Issue by Lc5** [enriquepiatti/Magicento#42]
PhpStorm version 6.0
Build PS#-127.100
JDK: 1.7.0_17

**Comment by michaJlS** [comment]
I have the same problem on PHPStorm 5.0.4.

**Comment by grisha87** [comment]
Same here~!

**Comment by enriquepiatti** [comment]
Fixed in 1.4.2

**Comment by Lc5** [comment]
Thanks! It's working for me now.

**Comment by grisha87** [comment]
Just updated my installation - great thanks for the quick fix Enrique!
