### ISSUE TITLE
Meta defination from Mage_Core_Block_Abstract::helper

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#43]
Class Mage_Core_Block_Abstract has method helper, that returns object of Mage::helper.

Example in block:

``` php
if($this->helper('wishlist')->isAllow()) {
    ...
}
```

When I click to "isAllow" PhpStorm takes me message: 
`Cannot find declaration to go to`
Could you make support of this method?

**Comment by enriquepiatti** [comment]
Done in v.1.6.0
