### ISSUE TITLE
Copy / Create / Switch template to theme folder

### ISSUE THREAD

**Issue by ScreamingDev** [enriquepiatti/Magicento#46]
If the current file is something from the base like

app/design/frontend/base/default/template/persistent/checkout/onepage/billing.phtml

then there should be an option "Go to template".

When there are multiple themes or no themes: Let user choose. Let there be a input box where you can define a new theme (name). Those two things can be combined in one textarea.

When there is one theme and the file is given: Jump to it.
## 

Currently I do CTRL+ALT+SHIFT+C to have the reference. Goto root dir of the project and make ALT+INSERT -> File, Paste the filename and turn "base/default" to "default/foo".
Back to the base file, copy content, to the new, paste, done.

Having this in ALT+M and as Option "Go to template" would be so great. Could be interesting for Block, Controller and Model too later on.

**Comment by enriquepiatti** [comment]
I think I didn't understand this Mike, right now there is an action for copying the template inside another package/area, just use ALT+M inside the .phtml you want to copy and select "Copy Template", is that what you need?

**Comment by ScreamingDev** [comment]
This is it but only allows existing templates etc. A input with autocomplete instead of dropdown would be great.

**Comment by enriquepiatti** [comment]
I think is better to have a dropdown for the package and theme, it's less prone to errors and faster than an input, and is not so hard to create those folders manually (when you have the folder for your custom package/them then it will appear in the dropdown).
Anyway, in Magento v2.1.0 you can now change the final path for the template, and also you can create the template using ALT+ENTER from the template attribute on layout .xml files (or any other text representing a relative path to some .phtml file which doesn't exist yet)
