### ISSUE TITLE
Add support for the 1.8/1.13 $_factory Mage factory method wrapper for 

### ISSUE THREAD

**Issue by Vinai** [enriquepiatti/Magicento#49]
In 1.8 and 1.13 many classes may receive a factory constructor argument as follows:

```
public function __construct(array $args = array())
{
    $this->_factory = !empty($args['factory']) ? $args['factory'] : Mage::getSingleton('catalog/factory');
}
```

There are slight variations like

```
$this->_factory = !empty($args['core_factory']) ? $args['core_factory'] : Mage::getSingleton('core/factory');
```

According to the core team, the purpose of these factory instance arguments is to make it easier to mock instances during testing. Since Magento 2 implements a form of DI this will not be ported to there.

All of these factory classes implement the following wrappers for the factory methods in `Mage`:

```
    /**
     * Retrieve model object
     *
     * @param string $modelClass
     * @param array|object $arguments
     * @return bool|Mage_Core_Model_Abstract
     */
    public function getModel($modelClass = '', $arguments = array())
    {
        return Mage::getModel($modelClass, $arguments);
    }

    /**
     * Retrieve model object singleton
     *
     * @param string $modelClass
     * @param array $arguments
     * @return Mage_Core_Model_Abstract
     */
    public function getSingleton($modelClass = '', array $arguments = array())
    {
        return Mage::getSingleton($modelClass, $arguments);
    }

    /**
     * Retrieve object of resource model
     *
     * @param string $modelClass
     * @param array $arguments
     * @return Object
     */
    public function getResourceModel($modelClass, $arguments = array())
    {
        return Mage::getResourceModel($modelClass, $arguments);
    }

    /**
     * Retrieve helper instance
     *
     * @param string $helperClass
     * @return Mage_Core_Helper_Abstract
     */
    public function getHelper($helperClass)
    {
        return Mage::helper($helperClass);
    }
```

It would be great if you could add support for calls to `$this->_factory->getModel()` to be the same as to `Mage::getModel()` and the other factory methods respectively.

On a more personal note, it's really a shame this type of fix is added to enable easier tests, when @IvanChepurnyi already implemented injecting mocks for calls to factory methods in EcomDev_PHPUnit.
This is true also since it adds another breaking point for the new PHPStorm meta factory class map which only supports static methods.

**Comment by enriquepiatti** [comment]
Done in v1.7.1
