### ISSUE TITLE
Compare With Original: Allow to Choose Different Theme / codePool

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#5]
- When I am in a core file, it still offers the option "Compare with Original" but showing "File are identical"
- Maybe there should be also an option "Compare with overwritten files" ?

**Comment by amenk** [comment]
In addition it would be nice to be able to compare template of package X with template of package Y - not just with the originals

**Comment by amenk** [comment]
One additonal thing:

When I have a template enterprise/foobar/template/foobar.phtml which does not exist in base/default but in enterprise/default, it does not offer the compare with original option

**Comment by amenk** [comment]
What do you think about that? I think the "compare with another package" or "another codePool" (for .php files) should not be so complicated? 

I would love this feature..

**Comment by enriquepiatti** [comment]
Yes, I will do that Alexander :+1:  (I hope in the next release), but it's really difficult to find free time for working on Magicento :(
In my last update I've added the full list of features to www.magicento.com, using Magicento on my work is saving me near 3h/week but many times I'm using more than that developing Magicento :S

**Comment by amenk** [comment]
In addition it would be interesting to navigate between the different fallback level: Just an open in other package ... Could also work for folders.

**Comment by amenk** [comment]
_bump_ .. is that complicated? I think it would be an easy feature + huge timesaver when messing arround with different themes.

**Comment by amenk** [comment]
Actually support for a 3-way compare would be awesome...

**Comment by enriquepiatti** [comment]
I've added a new action in v2.1.0 for comparing templates with the same relative path but in a different package or theme.
Regarding to the fallback jump I think it's easier to copy the file path of the current file and use CTRL+SHIFT+N

**Comment by amenk** [comment]
great! just discovered the feature today...

**Comment by enriquepiatti** [comment]
You can see the new features here:
http://magicento.com/#features
And also going to File > Settings > Plugins > (select Magicento and see the right panel)
