### ISSUE TITLE
Rewrite Method

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#50]
I love the rewrite class feature (even when trying to always use events, it is just not always possible).

What about a "Rewrite Method" action, which does first a rewrite class, and then adds a stub, for example like this:

<pre>

class Foo_Module_Block_Adminhtml_Widget_Form extends Mage_Adminhtml_Block_Widget_Form {

    protected function _setFieldset($attributes, $fieldset, $exclude=array())
    {
        $parentResult = parent::_setFieldset($attributes, $fieldset, $exculde);

        return $parentResult;
    }

}
</pre>

Yes, I am lazy. Sorry. :-)

**Comment by enriquepiatti** [comment]
hmmm... yes I agree, you are lazy ^_^
I will try to add this too, but just a tip (just in case you don't know it), you can use Ctrl+O to override parent methods in PHPStorm.

**Comment by amenk** [comment]
I did not know Ctrl+O - that is basically exactly what I asked. It even adds the parent call with parameters. To press two shortcuts is absolutely okay :-) Thank you!
