### ISSUE TITLE
Add template variable substitution for the current module

### ISSUE THREAD

**Issue by NicoSiebler** [enriquepiatti/Magicento#55]
Hi.

I think this feature does not exist yet as I did not come across any hints about this yet while searching.

I would appreciate if we could set some predefined variables like:

${MAGENTO_MODULE_VERSION} -> version from etc/config.xml if resolution possible
${MAGENTO_MODULE_NAMESPACE} -> namespace of the current module tree if resolution possible
${MAGENTO_MODULE} -> module name of the current module tree if resolution possible

which would be substituted with the current module context data when creating new files using the file templates as well as using live templates which would be helpful for history and debugging cases with PHPDoc comments for example. Considering the right variable syntax for the right section of course. 

For live templates this could be a function in the "Edit variables" popup window if this is possible.

**Comment by enriquepiatti** [comment]
Available in File Templates from v2.1.0 (will be released soon, PhpStorm will inform you about it)
