### ISSUE TITLE
Method 'getProduct()' not found in Varien_Event

### ISSUE THREAD

**Issue by realchriswells** [enriquepiatti/Magicento#58]
I'm not sure if you can file this one under 'stupid' or not, but I've been watching the Magento U Fundamentals of Magento course and in the chapter about Event/Observers, they use $product = $observer->getProduct(); yet when I put it in to PHPStorm with Magicento the code inspector tells me that it isn't valid, and that getProduct() does not appear in Varien_Event.

The bit that confuses me, is that the code still had the desired effect on the front end...

Is there a reason for this? Is it a bug in Magicento or just a crazy thing in Magento?

**Comment by enriquepiatti** [comment]
no, it's ok, that's how Magento works, see Varien_Object and their magic methods (that's why I called my plugin Magicento at really :P, but it doesn't help in this particular case)
