### ISSUE TITLE
File Header Generation - Module Name

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#59]
In our file / class templates we usually write

@package Namespace_Module
@category Namespace

would it be possible to fetch those from the current module where a file is created to include those as variables in the file templates?

I am afraid there are no such extensionpoints in PHPstorm? but maybe there are?

**Comment by amenk** [comment]
I saw that in the filetemplate magicento_module already the variable ${MODULENAME} is used.
But this is not evaluated when I add it to PHP File / PHP Class.
Basically this ${MODULENAME} has just to be made available to other files as well.

**Comment by enriquepiatti** [comment]
Since v.2.3.0 you can use ${MAGENTO_MODULE_VERSION}, ${MAGENTO_MODULE_NAMESPACE}, and ${MAGENTO_MODULE} in your File Templates

**Comment by amenk** [comment]
lovely -- but one small thing: #76
