### ISSUE TITLE
Jump between block files and template files

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#6]
When in a block class, search the layout XML files for occurrences where that class is used an offer a function to jump to the templates that use that block

The same when I am in a block -> jump to the classes

I know that can not be complete as templates can also be set programmatically but I would sure help.

**Comment by enriquepiatti** [comment]
Last release includes a lot of Layout functionalities, please check this video:
http://www.youtube.com/watch?v=2abUN40PfI0
