### ISSUE TITLE
Controller rewrite misses original controller include 

### ISSUE THREAD

**Issue by Bravehartk2** [enriquepiatti/Magicento#60]
When rewriting a controller, it is required to include the original file before class definition.

In the actual version this step is missing.

**Comment by enriquepiatti** [comment]
Could you send a screenshot of that? it's working fine to me.
![rewrite_controller](https://f.cloud.github.com/assets/1512470/578178/e27d9f8e-c84c-11e2-8d7f-87c74de916a0.png)

**Comment by Bravehartk2** [comment]
Hello,
I had exactly the same screens except the require_once line in the controller file. 

I don´t now if it metters but I use PHPStorm v.6.0.2 on an Mac OS X 10.8.3.

Is it possible, that there are such module preferences that can cause this behavior?

Big THX for your support!

Kind regards,
Marcel Lange

**Comment by enriquepiatti** [comment]
Exactly the same controller? are you trying it in a virgin Magento? (anyway, it should work everywhere but just in case for testing...)
Also check your template:
File > Settings > (IDE Settings) File and Code Template > Java EE > magicento_comtroller
it should be something like

<?php
#parse("PHP Header.php")
#if(${REQUIRE} != "")

require_once '${REQUIRE}';

#end

class ${CLASSNAME} #if(${EXTENDS} != "")extends ${EXTENDS}#end {

}

**Comment by Bravehartk2** [comment]
Hello again,
now I had the time to check it out. But it ist exactly how your wrote it:
<?php
#parse("PHP File Header")
#if(${REQUIRE} != "")

require_once '${REQUIRE}';

#end

class ${CLASSNAME} #if(${EXTENDS} != "")extends ${EXTENDS}#end {

}

I´ve tested it on a fresh Magento 1.7.0.2. Perhaps there is a collusion with an other plugin?

**Comment by enriquepiatti** [comment]
hmmm... no I don't think so, it's weird because everything works except the "require_once" part right? I mean the classname, and extends and the file header are included correctly? (remember you need to select the "Extends" class on the "Rewrite Controller" popup window)
Does that happen with all the controllers you are trying to rewrite?

**Comment by enriquepiatti** [comment]
Hi @Bravehartk2 are you still seeing this problem? which version of Magicento are you using? 
Let me know so I can close the bug if it's working fine now...

**Comment by Bravehartk2** [comment]
Hi  enriquepiatti,
it seems to work now. I've testd version 2.0.0 in combination with PHPStorm 6.0.3.

Thank you very much!!!
