### ISSUE TITLE
Toggle template hints doesn't work

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#66]
```
17:08:22 Magicento Notification: Template hints are now Disabled
17:09:07 Magicento Notification: Template hints are now Disabled
17:09:10 Magicento Notification: Template hints are now Disabled
17:09:18 Magicento Notification: Template hints are now Disabled
17:09:25 Magicento Notification: Template hints are now Disabled
```

I tried to enable Template hints via context menu, but it doesn't work. No idea how to debug this. It is a EE 1.12.0.2 if this is important. In other magento CEs it works.

If I can help you debug this tell me :-)

Thanks for fixing

**Comment by enriquepiatti** [comment]
Hi, what is your PHP configuration? (File > Settings > Magicento)
If you are using the PHP Interpreter please try with the HTTP instead, and make sure the eval.php is accessible from the URL you are using.
For example if you are accessing to your Magento using this:
http://local.mymagento.com
Then put that URL in "Url to Local Magento" field
And also check with your browser if you have access to:
http://local.mymagento.com/.idea/magicento/eval.php or http://local.mymagento.com/var/magicento/eval.php (depending if you chose .idea or var folder)
If everything is OK, check the code for the eval.php in your magento, you can also edit that file from PHPStorm, and use breakpoints for debugging it when accessing to it directly with your browser, you can check in that way why is not working properly.
Let me know if you find something wrong (y)

**Comment by Schrank** [comment]
```
Magicento: enabled
absolute path: correct
php exection enabled
use PHP interpreter
absolute path to php interpreter (empty and working in other projects)
```

I changed to http, added the URL and put the eval.php in var, now everything works.

argh. I think I'm an idiot. This is my first vagrant project, therefore the database is in the VM. Thanks for your support!

**Comment by r-martins** [comment]
worked for me too. thank you.
