### ISSUE TITLE
Create Module for Modman

### ISSUE THREAD

**Issue by jonpday** [enriquepiatti/Magicento#69]
Related to #65, it would be convenient to be able to place the new files from the "Create Module" command in a new `.modman/Namespace_Modulename` folder along with the `modman` file to specify the symlinks into `app/code` and `app/etc/modules` etc.

**Comment by Rokko11** [comment]
Yes, that would be very convenient! +1

**Comment by andreasemer** [comment]
+1 From me, it would be very good to get modman support. Our file structure is like in the screenshot http://www.mothership.de/sites/default/files/modman-support.png We get a errormessage, if we start Phpstorm.

**Comment by janssens** [comment]
+1 using magicento & modman would be great

**Comment by enriquepiatti** [comment]
This should be supported, normally Magicento will detect automatically if it's a modman project, but if not you can edit the settings, and configure the different paths where your Magento code is, and set a default path where all the files from Magicento will be created. The only restriction is to have the same normal folder structure from Magento in your modman folder (that is, app/code etc)

**Comment by janssens** [comment]
@enriquepiatti thank's for the tips, it's not detecting automatically my modman setup, but it's working perfectly after editing settings. Thanks for your amazing work and for the reply, enven on this old lost thread... cheers from France
