### ISSUE TITLE
[Ui] [Easy-Task] I can't read some config settings

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#70]
they are to long ...
![screenshot_selection_012](https://f.cloud.github.com/assets/1087128/742937/97338048-e3db-11e2-816f-bb0f25d92221.png)

**Comment by amenk** [comment]
Solution could be to shorten the title and put more info to the note under the edit box

**Comment by enriquepiatti** [comment]
Fixed in 2.1.0 (I've added tooltips).
You will get a notification in PhpStorm when the new version is available to download (and I will send an email too just in case).
