### ISSUE TITLE
Freeze when pressing Ctrl+B inside getChildHtml

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#71]
- PHPStorm 6.0.3
- Windows
- Project is on a Samba Network Share (I know this is not really supported - i can be slow but should not fully freeze)

Would an update to PhpStorm 7 EAP help?

For example we open 
`app/design/frontend/base/default/template/bundle/catalog/product/view/type/bundle.phtml` position the cursor on bundle_prices

`<?php echo $this->getChildHtml('bundle_prices') ?>`

and press Ctrl+B -> total freeze

**Comment by enriquepiatti** [comment]
Hi Alex, it doesn't happen in my project (it goes to app\design\frontend\base\default\layout\bundle.xml line 207).
Could you try in another project? do you see any error? maybe in the logs:
[USER_FOLDER].WebIde60\system\log\
normally the "threadDumps" has the useful information (please remove all the logs first so you can easily find the last one)

**Comment by amenk** [comment]
There is no error - it just freezes. A special case is here, that we access the project from windows via samba on a debian box. I will mail you the latest threadDumps.

**Comment by enriquepiatti** [comment]
Oh I have not read your last comment, I think that is exactly the problem Alex, the error appears is when trying to list the folders (for getting the available packages and themes). I will try to find a solution for this, but I'm not sure if it will be possible, I think I will need to add special code for identifying and managing Samba files, etc.
Could you provide more information about your environment? you don't have the project in your local file system? (If I understand it correctly you are under windows right?). Which is the path for Mage.php?

**Comment by amenk** [comment]
Actually it is not me, but one of my co-workers. He is working on WIndows, the full source code is located on a Linux box which is serving the file system via Samba to Windows.

**Comment by enriquepiatti** [comment]
Well I think the only solution right now for that is to use local files and maybe configure a deployment server to the Linux box so it's sync automatically.
