### ISSUE TITLE
Toggle Template hints should trigger refresh of config cache

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#72]
After enabling the template hints, the config cache needs to be refreshed (if enabled), at least for the EE.

Just saw the Flush Cache in the menu... Not more important for me, but you should think about. Toggle template hints is useless if the cache is not refreshed afterwards :-)

**Comment by enriquepiatti** [comment]
hmmm.... yes but I think the action will run a bit slower if we don't need to flush the cache (because it's already disabled for example). In my system is taking 3 sec without flushing the cache and 4 sec with flush cache.
Not a big difference, I'm bit indecisive ^_^

**Comment by enriquepiatti** [comment]
Also remember you can now write your own PHPScripts, you could check the eval.php generated for the toggle template hints, and also the eval.php generated for the flush cache, and create your own script for doing both things in just one.
http://magicento.com/#magicento-php-scripts

**Comment by enriquepiatti** [comment]
OK I will add the flush cache to the template hints (but it will be executed only if FPC is enabled). Anyway, I hope you can see and test the php scripts feature, it could be useful for adding custom features, and maybe sharing them with the rest of the users.

**Comment by Schrank** [comment]
Sure I can, I'm a big fan and was very happy to spent money :-) I have only the Config cache enabled which needs to be refreshed. FPC ... hmm never tried it on my dev machine. Good hint.

I'll check the scripts, thanks :)
