### ISSUE TITLE
List of modules displayed when rewriting a Class is unsorted

### ISSUE THREAD

**Issue by jonpday** [enriquepiatti/Magicento#73]
After choosing "Rewrite Class" from the Magicento context menu, the options in the drop-down are unsorted and difficult to navigate. It would be helpful for this list to be sorted alphabetically.

**Comment by enriquepiatti** [comment]
I see them sorted alphabetically, you can also start typing the module name when the dropdown is open, anyway, I agree is important to have the list sorted, what OS are you using?
I will reinforce a sort just in case.
![rewritedropdown](https://f.cloud.github.com/assets/1512470/819129/9d8a6c82-efab-11e2-8c42-e5b8e823ec10.png)

**Comment by jonpday** [comment]
Thanks Enrique, we are on Ubuntu 12.04 with Oracle Java (`Java(TM) SE Runtime Environment (build 1.8.0-ea-b97)`). Here is a screenshot: 
![screenshot from 2013-07-19 12 21 02](https://f.cloud.github.com/assets/752408/824010/e53db9b6-f02e-11e2-8f63-25eda0e360db.png)

Hope that helps.

**Comment by jonpday** [comment]
works great in the new version, thanks @enriquepiatti
