### ISSUE TITLE
Module variables also for class docblocks etc.

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#76]
Steps to reproduce:
- Settings -> File and Code Templates
- Includes
- Choose PHP Class Doc Comment
- Add " \* @package ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}"

Now browse to a class in the code, position the cursor before it and type "/*\* <ENTER>"

The variables are not replaced.

**Comment by enriquepiatti** [comment]
Sorry I couldn't find how to do that, the new variables are available only for new File templates, no for includes, the are not extension point for that part and the code is not open source either.

**Comment by amenk** [comment]
:( shall we ask JetBrains?

**Comment by enriquepiatti** [comment]
hmm... yes I think you could request an extension point for that part, without that is not possible to do this

**Comment by cmuench** [comment]
Please note that live templates have another variable syntax.

`${MAGENTO_MODULE_NAMESPACE}` should be `$MAGENTO_MODULE_NAMESPACE$`

**Comment by enriquepiatti** [comment]
it doesn't matter, that's not the reason why the template vars are not working inside Includes, there are no extension point for the includes, so I can't add code to that part.

**Comment by cmuench** [comment]
@enriquepiatti yes. I understood it. It was only a hint related to the issue description.
