### ISSUE TITLE
Flushing APC Magento Cache

### ISSUE THREAD

**Issue by dabrowiecki** [enriquepiatti/Magicento#85]
Hi,

I am using APC as a fast magento cache, but it is not flushed when I use Magicento's Flush Magento Cache feature.

**Comment by enriquepiatti** [comment]
I haven't tried that, but you can easily fix this using the Magicento Php Scripts feature: http://magicento.com/#magicento-php-scripts
You can create your own PHP script for flushing APC, you don't need to be worried about to include Magento in your PHP script or how to execute it, Magicento is doing that, you just type the code for flushing APC and then execute the script using ALT + M > Execute PHP Script (and select your flush APC script).
If it works fine you could share that script (it will be signed with your username) too so it can be used by other Magicento users too.

**Comment by enriquepiatti** [comment]
Closing this because it's specific for some projects, so it's better to use a custom Magicento PHP Script for this (or reuse some script uploaded by another user)
