### ISSUE TITLE
Missing autosuggests

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#86]
1. for 1st argument of`Mage_Core_Model_Resource_Setup::getIdxName`
2. for 1st argument of `Mage_Core_Block_Template::setTemplate`
3. for 1st argument of `Mage::getConfig()->getBlockClassName`

**Comment by enriquepiatti** [comment]
Is this a feature request?

**Comment by Koc** [comment]
yes

**Comment by enriquepiatti** [comment]
Done in v2.5
