### ISSUE TITLE
New Module

### ISSUE THREAD

**Issue by krovak** [enriquepiatti/Magicento#9]
When generate new module, Magicento create new project on new directory Mag, not in actual project.

**Comment by enriquepiatti** [comment]
Krovak can you explain better the issue? also the steps you are following and the settings you have in File > Settings > Magicento.

**Comment by krovak** [comment]
Project path is: /home/mimo/Dokumenty/Programovani/Magento/1.7.0.2
Press Alt + M -> Create Module (magicento_001.png)

Fill dialog (magicento_002.png)
Namespace = Iguru,
Module = Test

Files is generate fine, but in
/home/mimo/Dokumenty/Programovani/Mag/app....  (magicento_003.png)

Setup magicento is magicento_004_setup.png

With best regards
Michal Moc

2012/10/2 epiattisumma notifications@github.com

**Comment by krovak** [comment]
ok, attachements are deleted by github, now is on adress:
http://iguru.eu/skola/magicento/magicento_001.png
http://iguru.eu/skola/magicento/magicento_002.png
http://iguru.eu/skola/magicento/magicento_003.png
http://iguru.eu/skola/magicento/magicento_004_settings.png

**Comment by enriquepiatti** [comment]
The problem is on your Magicento settings. You need to put the path to Mage.php, for example in your case it should be:
/home/mimo/Dokumenty/Programovani/Magento/1.7.0.2/app/Mage.php

The strange thing here is that Magicento should throw an Exception when you put the wrong path, are you using the last version?

**Comment by krovak** [comment]
ok, if i try small path (only "/home/mimo/TestMagicento") modul create
project on "/home/mimo/T"

PhpStorm 5.0.1
JDK: 1.6.0_26

my colleague test it on

PhpStrom 5.0.2
JDK 1.7.0_07

and its work fine.

I try update and tested.

2012/10/2 epiattisumma notifications@github.com

**Comment by enriquepiatti** [comment]
Sorry krovak, I've updated my answer and I think you've read the older one, please check my answer above again, you need to set the correct pathto Mage.php

**Comment by krovak** [comment]
Ok, ok, ok. Sorry for this spam :-/ if i change path for /home/mimo/Dokumenty/Programovani/Magento/1.7.0.2/app/Mage.php it's work fine!!!!

browse button would be nice... ;-)
