### ISSUE TITLE
NullPointerException when accessing Magicento and cursor placed on EOF

### ISSUE THREAD

**Issue by martinhelfert** [enriquepiatti/Magicento#93]
I get a

```
NullPointerException: Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=77,keyText=M,keyChar='µ',modifiers=⌥,extModifiers=⌥,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame3
```

when I try to open Magicento's menu and the cursor is placed on the very last position in any file (like where you get when you press `fn+cmd+cursor-right` on a mac). Clicking somewhere else inside the file and the menu will open just fine.

Using
Magicento 2.4.0
PHPStorm 6.0.3 Build #PS-129.814
JRE 1.6.0_51
OSX 10.8.5

**Comment by enriquepiatti** [comment]
Duplicate: https://github.com/enriquepiatti/Magicento/issues/84
